kubeflow/spark-operator

pkg/controller/controller.go, pkg/crd/crd.go, pkg/initializer/initializer.go
When the operator is stopped and started, the CRD definition stays the same. There is a problem with this: changes to the CRD definition won't take effect if the definition is not updated to the API server. Deleting the definition when the operator stops and recreating it when the operator starts effectively updates the definition.
=> Delete the CRD definition when the operator is stopped

pkg/config/constants.go, pkg/controller/submission.go
It simply doesn't make sense for the submission runner to wait for application to complete.
=> Do not wait for application to complete

pkg/apis/sparkoperator.k8s.io/v1alpha1/types.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/controller/spark_pod_monitor.go
When an upate to a SparkApplication object is received, the controller checks if the update was to the specification, and if so, kills the old run of the application by deleting the driver pod of the old run and submits the new run.
Ref #83 .
=> Added support for SparkApplication updates

pkg/apis/sparkoperator.k8s.io/v1alpha1/defaults.go, pkg/controller/controller.go, pkg/controller/controller_test.go
Instead of blindly submitting an application to run when `onAdd` is called, the controller checks if it should submit by testing if any of the following submission conditions is satisfied.  
* The application has not been submitted to run, i.e., its state is empty or `NEW`.
* The application has terminated and is subject to restart based on the observed application state and restart policy.
* The application has failed submission and is subject to submission retry based on the observed application state and submission failure tracking information. 
This is necessary for #90.
=> Check condition for submission in onAdd

docs/quick-start-guide.md
Without the `-n sparkoperator` I wasn't able to see the deployment.
wrt. `kubectl describe sparkapplication spark-pi` it just looks better, although the previous form was also working
=> Fix the typos in quick start guide and adding the namespace explicitly

pkg/controller/sparkapplication/controller.go
=> Explicitly delete the driver pod and UI service when a SparkApp gets deleted

pkg/config/constants.go
@ypzhang @akhurana001.
The Spark 2.2 fork use different names for some Spark config properties than Spark 2.3.0 in the upstream. This PR fixed the names of those properties to match those in https://github.com/apache-spark-on-k8s/spark/blob/branch-2.2-kubernetes/docs/running-on-kubernetes.md#spark-properties.
=> Fixed names of some config properties

pkg/controller/scheduledsparkapplication/controller.go
The driver pod gets deleted when the `SparkApplication` object of the old run gets deleted.
=> No need to delete the driver pod when deleting an old run of a scheduled app

main.go, manifest/spark-operator-rbac.yaml
Core DNS reached GA in Kubernetes 1.11. We cannot assume that users will always use the kube-dns add-on so the check no longer makes sense.
=> Removed check on the presence of kube-dns

Gopkg.lock, Gopkg.toml, README.md, docs/design.md, docs/quick-start-guide.md, docs/user-guide.md, hack/gencerts.sh, main.go, manifest/spark-operator-rbac.yaml, manifest/spark-operator-with-webhook.yaml, pkg/apis/sparkoperator.k8s.io/v1alpha1/types.go, pkg/config/constants.go, pkg/controller/sparkapplication/submission.go, pkg/util/util.go, pkg/webhook/certs.go, pkg/webhook/doc.go, pkg/webhook/patch.go, pkg/webhook/patch_test.go, pkg/webhook/scheme.go, pkg/webhook/webhook.go, pkg/webhook/webhook_test.go
This PR includes an initial commit for adding the mutating admission webhook that will replace the existing initializer for Spark pod customization. It also includes support for pod affinity/anti-affinity.
=> Add mutating admission webhook

docs/api.md, pkg/apis/sparkoperator.k8s.io/v1alpha1/types.go, pkg/controller/sparkapplication/submission.go
To cover `spark.driver.memoryOverhead` and `spark.executor.memoryOverhead`.
=> Added optional field MemoryOverhead

pkg/controller/sparkapplication/submission.go
Ensure Operator triggered spark-submit never waits for App completion.
=> Operator Spark-submit: Never Wait for Completion

docs/api.md, docs/user-guide.md, examples/spark-pyfiles.yaml, pkg/apis/sparkoperator.k8s.io/v1alpha1/types.go, pkg/config/constants.go, pkg/controller/sparkapplication/submission.go, sparkctl/cmd/create.go
This PR add a support for PySpark, and thus closes https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/181
@liyinan926
CC @prasanthkothuri
=> Add PySpark support to sparkctl and Spark Operator. 

Dockerfile, hack/gencerts.sh
Modified gencert.sh so that it can be run inside a pod container when running as a k8s Job. It can still be manually run the same way as before. This PR is to be reviewed together with this [commit](https://github.com/helm/charts/pull/6239/commits/de8d491d000edebc3bff1fc2c9c0b974d958b439).
=> Modified gencerts.sh script to be used in Helm chart automatic secret creation. 

Gopkg.lock, Gopkg.toml, sparkctl/README.md, sparkctl/cmd/create.go, sparkctl/cmd/gcs.go, sparkctl/cmd/s3.go
Adds support for staging local dependencies in sparkctl (solves #144 )
- Implementation follows the guidelines from Google Storage Interoperability (https://cloud.google.com/storage/docs/interoperability) and S3 CLI docs (https://docs.aws.amazon.com/cli/latest/topic/s3-config.html)
- By default, implementation uses `--upload-to-endpoint` set to `https://storage.googleapis.com` and `--upload-to-region` default empty region 
```
export AWS_ACCESS_KEY_ID=<redacted>
export AWS_SECRET_ACCESS_KEY=<redacted>
./sparkctl create \
./jobs/spark-pi.yaml \
--upload-to s3a://<gcs-bucket>
```
```
export GOOGLE_APPLICATION_CREDENTIALS=~/<redacted>.json
./sparkctl create \
./jobs/spark-pi.yaml \
--upload-to gs://<gcs-bucket>
```
@liyinan926 @prasanthkothuri
=> Add s3 support for staging local dependencies in sparkctl #144

pkg/controller/sparkapplication/controller.go, sparkctl/README.md, sparkctl/cmd/events.go, sparkctl/cmd/log.go, sparkctl/cmd/root.go, sparkctl/cmd/status.go, sparkctl/cmd/utils.go
SparkOperator will additionally 
trigger events on driver/executor `pending`, `running` and `unknown`.
Now `$ sparkctl events <name>` will trigger `watch` and display:
```
Events: Type	Reason	Age	Message
Normal	SparkApplicationAdded	1h	SparkApplication spark-pi was added, enqueued it for submission
Normal	SparkApplicationTerminated	1h	SparkApplication spark-pi terminated with state: COMPLETED
Normal	SparkDriverCompleted	1h	Driver spark-pi-1533304888525-driver completed
Normal	SparkExecutorCompleted	1h	Executor spark-pi-1533304888525-exec-1 completed
```
It is also good in early catching early mistakes
```
Normal	SparkApplicationDeleted	6s	SparkApplication spark-pi was deleted
Normal	SparkApplicationAdded	6s	SparkApplication spark-pi was added, enqueued it for submission
Warning …
```
=>  Extend sparkctl to stream SparkApplication events

Gopkg.lock, sparkctl/cmd/event.go, sparkctl/cmd/root.go
This is to be consistent with naming of the other subcommands.
@mrow4a
=> Changed subcommand events to event for sparkctl

docs/api.md, pkg/config/constants.go
`spark.kubernetes.pyspark.pythonversion` has been fixed and changed to `spark.kubernetes.pyspark.pythonVersion` in Spark.
=> Fixed the name of a Spark config key

sparkctl/cmd/create.go
As in the title @liyinan926 - I was getting:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1add8f9]
goroutine 1 [running]:
k8s.io/spark-on-k8s-operator/vendor/github.com/google/go-cloud/blob.(*Reader).Close(0xc4205c2460, 0x2211a00, 0xc420040090)
/Users/pmrowczy/Projects/go/src/k8s.io/spark-on-k8s-operator/vendor/github.com/google/go-cloud/blob/blob.go:42 +0x29
k8s.io/spark-on-k8s-operator/sparkctl/cmd.uploadHandler.uploadToBucket(0x21f7780, 0xc42027e2d0, 0x7ffeefbffac3, 0x14, 0x7ffeefbffadb, 0x1e, 0x20a5025, 0x2, 0x2211a00, 0xc420040090, ...)
```
=> Fix reader closing issue when err is not nil

sparkctl/cmd/root.go
I left the possibility to override it using the `k` flag. The logic to select the `KubeConfig` flag is in this file, so that in `cmd/client.go` `KubeConfig` is already set at its final value (as it is now)
=> add the KUBECONFIG check

sparkctl/README.md, sparkctl/cmd/create.go
Fixes: #233.
The command looks like the following:
```
sparkctl create <name of forced run> --from <name of ScheduledSparkApplication>
```
Note that the word `sparkapplication` is removed from the original proposal in #233, as we currently don't have support for `ScheduledSparkApplication` in `sparkctl` so that keyword is not really necessary for now. 
@spjegan @dharmeshkakadia
=> Added support for creating a SparkApplication from a ScheduledSparkApplication

Dockerfile
If your intention were to just install the packages, you don't need to cache anything locally.
just install them with the --no-cache option in apk add.
All the best,
Benjamin
=> remove alpine package caching

Dockerfile, hack/gencerts.sh, main.go, pkg/webhook/webhook.go
This PR needs to be merged first and the image `gcr.io/spark-operator/spark-operator:v2.4.0-v1alpha1-latest` needs to be rebuilt and pushed. After that I'll make a PR with these [changes](https://github.com/helm/charts/compare/master...yuchaoran2011:fixwebhook) against helm/charts repo. Because only after the new image is pushed will the helm/charts CI pass on my PR.
I also made the MutatingWebhookConfiguration name configurable. We have a use case where two teams each has an operator instance running in their own namespace. The team who installs the operator later would override the webhook configuration of the team who deployed earlier.
Fixed #335
=> Fixed webhook

pkg/controller/sparkapplication/controller.go, pkg/controller/sparkapplication/sparkapp_util.go
The operator currently adds a finalizer to a submitted `SparkApplication` object for the purpose of preventing it from being deleted before the driver pod is gone (the operator does try to delete the driver pod when deletion of the `SparkApplication` is requested). The purpose of this is to make sure the driver pod is deleted when the `SparkApplication` gets deleted without relying on an `OwnerReference`. Previously the operator deleted the driver pod and other relevant k8s resources when `onDelete` is called. 
Using a finalizer on a custom resource risks running into this issue: https://github.com/kubernetes/kubernetes/issues/60538 for some versions of Kubernetes. I propose here to remove the use of the finalizer and simply delete the resources when `onDelete` is called. This might risk …
=> Removed the use of the finalizer

Dockerfile, Dockerfile.rh, examples/spark-pi-prometheus.yaml, examples/spark-pi.yaml, examples/spark-py-pi.yaml
1. Upgraded Go to 1.11.5
2. Added required `sparkVersion` in the SparkApplication examples. Otherwise [validation](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/commit/4d6f9a059b86238192421268dc2384f353754383#diff-d1c35bf2dffda85b37b85868c24d9421R157) would fail.
=> Minor fixes to CRD validation

docs/user-guide.md
I could not find what `secretType` I had to use if I didn't need any special configuration handling and I ended up having to look it up in the source code. I added a single line to help people find this information.
=> Update the user guide with info on the default secretType

Dockerfile.rh
Due to a known [issue](https://github.com/moby/moby/issues/34129#issuecomment-315856425) with Moby, which is used to build the OpenShift operator image, parameterizing the USER caused the operator image to have the `root` user no matter what ARG is set. So for now, hard coding the USER to 185/JBoss for the OpenShift image is unfortunately the only option.
=> Hard code the USER in OpenShift Dockerfile to 185

examples/spark-pi-prometheus.yaml, pkg/config/constants.go, pkg/controller/sparkapplication/monitoring_config.go, pkg/webhook/patch.go, pkg/webhook/patch_test.go, spark-docker/conf/prometheus.yaml
1. In the Prometheus spark-pi example YAML, added an argument of a large number to the spark-pi job. The purpose is to let the job run longer. Without it, the job finishes quickly, oftentimes without even generating any metrics, because the time is so short.
2. Fixed Prometheus pattern match error. #381 
3. Shortened the suffixes appended to the names of ConfigMaps and volumes. In our applications, we frequently run into an error like: 
```
Invalid value: "<my-custom-name-prefix>-prometheus-config-volume": must be no more than 63 characters
```
The suffix appended by the operator `-prometheus-config-volume` is too long. Making it shorter allows the user to have a longer portion to work with.
=> Various Prometheus-related fixes and improvements

Dockerfile.rh, sparkctl/build.sh, test/e2e/basic_test.go, test/e2e/framework/framework.go, test/e2e/main_test.go
- Updates the suite so it can use for example an arbitrary namespace and sa.
- fixes several minor issues
Example how it can be used with this patch:
- adds a build script for sparkctl
```
export SPARK_TEST_NAMESPACE=spark
export SPARK_TEST_SERVICE_ACCOUNT=spark-sa
export SPARK_TEST_IMAGE=<image>
go test -v ./test/e2e/ --kubeconfig "$HOME/.kube/config" --operator-image-pullPolicy=Always \
--operator-image=<image> \
--spark-test-namespace=spark --spark-test-image=<image> \
--spark-test-service-account=spark-sa
```
=> Update test suite to run against arbitrary configuration

docs/api.md, pkg/apis/sparkoperator.k8s.io/v1beta1/types.go, pkg/config/constants.go, pkg/controller/sparkapplication/monitoring_config.go, pkg/controller/sparkapplication/monitoring_config_test.go, pkg/webhook/patch.go, pkg/webhook/webhook.go, spark-docker/conf/prometheus.yaml
1. Added an API to pass custom Prometheus configuration file contained in a job image. The current APIs only support passing the contents of a custom Prometheus configuration file, but not the file name. The new API allows the user to bake his config file in the Spark job image and reference it in the job YAML.
2. Automatically truncate the volume name to fit 63 chars. This [PR](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/405) introduced a band-aid solution to shorten the suffixes appended by the operator. Now the operator simply truncates the volume name to be 63 characters if it's longer than 63. The user will no longer to experience a failed job because of this issue.
Both of these issues are what we faced in our internal applications using the operator at …
=> Support prometheus custom configuration file

pkg/controller/sparkapplication/controller.go
Fixes #417 
Verified it works by observing the expected behavior:
```
I0221 11:02:24.834853      11 controller.go:248] Starting processing key: "spark/spark-pi"
I0221 11:02:24.834887      11 controller.go:510] Trying to update SparkApplication spark/spark-pi, from: [{spark-application-1550746819628 2019-02-21 11:00:10 +0000 UTC 2019-02-21 11:02:21 +0000 UTC {spark-pi-ui-svc 31037    spark-pi-driver} {FAILING } map[spark-pi-1550746808866-exec-1:FAILED] 1 1}] to [{spark-application-1550746819628 2019-02-21 11:00:10 +0000 UTC 2019-02-21 11:02:21 +0000 UTC {spark-pi-ui-svc 31037    spark-pi-driver} {FAILING } map[spark-pi-1550746808866-exec-1:FAILED] 1 1}]
I0221 11:02:24.834980      11 controller.go:255] Ending processing key: "spark/spark-pi"
I0221 11:02:37.452601      11 controller.go:208] …
```
=> Set default values when creating a new app 

sparkctl/cmd/client.go
Fixes https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/419
=> Add InClusterconfig for sparkctl if no kubeconfig provided

pkg/config/constants.go, pkg/controller/sparkapplication/sparkapp_metrics_test.go, pkg/util/metrics_test.go, spark-docker/conf/prometheus.yaml
1. Fixed the escaping of the dot separator between the namespace and the app name in the metric names.
2. Changed `app_name` to `app_id` to be consistent with the naming in the Spark Prometheus [configuration](https://github.com/prometheus/jmx_exporter/blob/master/example_configs/spark.yml).
=> Prometheus: Fixed separator escaping. Renamed field

.travis.yml, Dockerfile, Dockerfile.rh, Gopkg.lock, Gopkg.toml, examples/spark-pi-configmap.yaml, examples/spark-pi.yaml, manifest/spark-operator-with-webhook.yaml, manifest/spark-rbac.yaml, pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1alpha1/fake/fake_scheduledsparkapplication.go, pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1alpha1/fake/fake_sparkapplication.go, pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1beta1/fake/fake_scheduledsparkapplication.go, pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1beta1/fake/fake_sparkapplication.go, pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go, pkg/util/metrics.go, sparkctl/cmd/event.go, test/e2e/framework/config_map.go, test/e2e/framework/deployment.go, test/e2e/framework/framework.go, test/e2e/framework/job.go, test/e2e/framework/role.go, test/e2e/framework/role_binding.go, test/e2e/framework/service.go, test/e2e/framework/service_account.go, test/e2e/main_test.go, test/e2e/volume_mount_test.go
* Added an integration test for mounting a ConfigMap. This is a common scenario that we used to check manually. Currently webhook is required. But the test can be adapted with minimal changes once pod template is supported in the operator.
* Many minor bug fixes and improvements in the test code.
* Upgraded Kubernetes Go client version to 1.13.4.
* Upgraded dep to 0.5.1
=> Refactored integration tests

test/e2e/README.md, test/e2e/volume_mount_test.go
1. In my previous PR, the two integration tests run in parallel. Because both jobs have the same name `spark-pi`, they would cause conflicts with each other (e.g. The first test is finished and then deletes the sparkapp `spark-pi`, while the second test is still running). The fix can be either renaming the sparkapp names in the YAMLs, or making them run sequentially.
2. Added missing content in tests README.
=> Made tests run sequentially

pkg/apis/sparkoperator.k8s.io/v1beta1/types.go, pkg/config/constants.go, pkg/controller/sparkapplication/controller.go, pkg/controller/sparkapplication/spark_pod_eventhandler.go, pkg/controller/sparkapplication/spark_pod_eventhandler_test.go, pkg/controller/sparkapplication/sparkapp_util.go, pkg/controller/sparkapplication/submission.go
=> Added a submissionID to status and use it to group pod of the same run

test/e2e/README.md, test/e2e/framework/framework.go, test/e2e/framework/job.go
1. The gencerts job needs to be cleaned up once completed. Not doing so would potentially cause the tests to fail, because this [line](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/test/e2e/framework/framework.go#L148) checks that the first pod it sees to be in "RUNNING" status.
2. The gencerts job image wasn't being configured. Now it's fixed.
=> Fixed gencert job in e2e tests

pkg/apis/sparkoperator.k8s.io/v1beta1/types.go, pkg/webhook/patch.go, pkg/webhook/patch_test.go
Support specify scheduler name in `SparkPodSpec`, for issue #463 .
=> Support scheduler name 

manifest/spark-operator-crds.yaml, pkg/crd/sparkapplication/crd.go
=> Limit SparkApplication name to 63 characters in JSON schema validation

manifest/spark-operator-rbac.yaml
After installations of the operator, the `admin` role will not have any permissions to use `sparkapplications` or `scheduledsparkapplications`.
Using `rbac.authorization.k8s.io/aggregate-to-admin: "true"` annotation with `sparkoperator-aggregate-to-admin` will add these permissions to the admin role. This is very useful when you assign admin role for service accounts or users to allow them to use the operator without any extra RBACs.
=> Add sparkapplications, scheduledsparkapplications permissions to admin

pkg/webhook/patch.go, pkg/webhook/patch_test.go
#464 patch assumes that the scheduler name of created pod would be empty in default which is not true, this patch fixes it.
=> Fix scheduler name doesn't work when specified

pkg/config/constants.go, pkg/controller/sparkapplication/controller.go, pkg/controller/sparkapplication/controller_test.go, pkg/controller/sparkapplication/sparkapp_util.go, pkg/controller/sparkapplication/submission.go
and try getting the driver pod from the API server when it's not found in the informer cache.
@akhurana001 this should solve the issue addressed in https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/495.
=> Record driver pod name during submission

docs/user-guide.md, pkg/apis/sparkoperator.k8s.io/v1beta1/types.go, pkg/apis/sparkoperator.k8s.io/v1beta1/zz_generated.deepcopy.go, pkg/webhook/patch.go, pkg/webhook/patch_test.go
Hi, this pr adds `hostNetwork` option for driver and executor, according to https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/451 .
=> Add hostNetwork option for driver and executor.

pkg/apis/sparkoperator.k8s.io/v1beta1/types.go, pkg/controller/sparkapplication/controller.go, pkg/controller/sparkapplication/controller_test.go, pkg/webhook/patch.go, pkg/webhook/patch_test.go
Hi!
The following PR enables to have node selector filters at Pod level https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
This is useful when you want your executors in a different type of nodes than the driver.
=> Added support for node selector at SparkPod level

docs/who-is-using.md
We're started using spark operator in place of spark jobserver in production for ELT type of data pipelines. We even created a skuber extension to make it easy for communicating with spark operator on kubernetes using scala - https://github.com/stacktome/skuber-spark-operator.
=> Whos using update stacktome

docs/user-guide.md, pkg/apis/sparkoperator.k8s.io/v1beta1/types.go, pkg/webhook/patch.go, pkg/webhook/patch_test.go
This PRs adds the option to specify DNSConfig as defined in [k8s api](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#poddnsconfig-v1-core)  for the Driver and the Executor pods. 
It adds the objects in the api and modifies the weebhook
=> Added DNS config option for the driver and executor pods

docs/who-is-using.md
We're using spark-on-k8s-operator for 5 months now, and are very happy with it.
The feature which is most important for us is the ability to run Spark jobs on a dedicated node pool.
Before the operator we used Spark on K8S in client mode, both streaming using Deployment, and batch using CronJobs.
=> Add Bringg to who-is-using.md

docs/api.md, docs/quick-start-guide.md, pkg/apis/sparkoperator.k8s.io/v1alpha1/types.go, pkg/apis/sparkoperator.k8s.io/v1beta1/types.go, pkg/controller/sparkapplication/controller.go, pkg/controller/sparkapplication/sparkui.go, pkg/controller/sparkapplication/sparkui_test.go
@liyinan926 Removing NodePort Service as we discussed.  I have updated `WebUIAddress` under Status in CRD to `<CLUSTER-IP>:<PORT>` which will be accessible only from within the cluster.
As expected, this is non-backward compatible. I am not sure if any other SparkOperator user might be depending on the node-port service to access the UI.
Let me know your thoughts on this.
=> Replace NodePort Service with ClusterIP

pkg/webhook/patch.go
Address partially #505, at least on Openshift.
=> Allow pod sec context to be overridden

pkg/apis/sparkoperator.k8s.io/v1beta1/types.go, pkg/controller/sparkapplication/controller.go
Currently we don't reset `ExecutionAttempts` upon a successful run of an application. This cause the counter to quickly reach the retry limit if it has previously failed several times. For example, assuming that an application failed 3 times in a row, and then succeeded once. If the retry limit on failures is 3, then the application will not be retried the next time it fails as its `ExecutionAttempts` has already exceeded 3. The semantics of ``ExecutionAttempts`, however, is a counter of failed attempts, and its value is used to determine if the controller should keep retrying running an application in case of failure, as the [code](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/pkg/controller/sparkapplication/controller.go#L421) shows. `The same goes for …
=> Reset ExecutionAttempts/SubmissionAttempts properly

pkg/controller/sparkapplication/controller.go, pkg/crd/crd.go, pkg/webhook/webhook.go
Prevents superfluous updates when semantically-equal objects are not equal in memory.
Specifically solves the following scenario that we were observing:
- User submits a SparkApplication with an empty slice in the spec
- The operator submits the application and updates the status field
- When the updated SparkApplication is marshaled, the field containing the empty slice is dropped due to `omitempty`
- When the SparkApplication is unmarshaled, the field is now `nil`, and the spec is considered changed, because `nil != []foo`
- The operator runs spark-submit a second time, deleting and recreating the driver pod
This is the function that k8s uses internally for semantic deep equality. See:
- https://godoc.org/k8s.io/kubernetes/third_party/forked/golang/reflect
- …
=> Use semantic DeepEqual for object comparison

pkg/controller/sparkapplication/controller.go
Reduces churn and queue size, especially under high load. See [this comment](https://github.com/kubernetes/client-go/blob/58ae7b3039c91cdf796bfcd07fd7f5958acaf345/tools/cache/controller.go#L170) about onUpdate.
=> Avoid enqueuing non-updated applications

Gopkg.lock, pkg/apis/sparkoperator.k8s.io/v1beta1/types.go, pkg/apis/sparkoperator.k8s.io/v1beta1/zz_generated.deepcopy.go, pkg/client/clientset/versioned/clientset.go, pkg/client/clientset/versioned/fake/clientset_generated.go, pkg/controller/sparkapplication/controller.go, pkg/controller/sparkapplication/controller_test.go, pkg/controller/sparkapplication/job.go, pkg/controller/sparkapplication/job_test.go, pkg/controller/sparkapplication/submission.go
Some changes for the multi-version branch (Ref: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/526):
-  Fix Controller tests & add tests for SubmissionJobManager.
-  Create interface for SubmissionJobManager and move `submissionCmdArgs` generation to within SubmissionJobManager.
- Add default resource limits for the Job pods. We use resourceQuotas on clusters which cause failures unless resource requests/limits are set on the job pod.
- Remove OnSubmissionFailureRetryInterval from v1beta1 spec.
I also see that now `FailedSubmissionState`  is terminal and we don't move it to `FailedState` or retry it even if the retryPolicy is `Always` . This is a behavior change compared to master, we can chat more if we want to update this.
PTAL @liyinan926  when you get a chance.
=> Multi Version Support via Job:  Add Tests + other changes 

pkg/controller/sparkapplication/job.go
This propagates `ImagePullSecrets/ImagePullPolicy` to the spark-submit-job. 
@liyinan926 PTAL and also let me know if I can help with anything else required to merge this branch into master.
=> Add ImagePullSecrets/ImagePullPolicy for submit job

docs/quick-start-guide.md
All WorkQueue metrics are based on the WorkQueue name which by default is set to `spark_application_controller`. For example, the metric `p.prefix + "_depth"` should result in `spark_application_controller_depth`. This change is so that the documentation reflects the metrics code correctly.
=> Updated prefixes in documentation to match produced metrics.

docs/volcano-integration.md
Add documents on volcano integration.
For #583
=> Add volcano integration docs

pkg/webhook/resourceusage/enforcer.go, pkg/webhook/webhook.go
Fixing the same issue as in https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/592, making sure the resourcequota/pod/sparkapplication callbacks are created before starting the informer.
(see https://github.com/kubernetes/client-go/issues/675)
=> Add resource quota callbacks before starting the informer

manifest/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml, manifest/crds/sparkoperator.k8s.io_sparkapplications.yaml
**Context:**
Running Python3 on a K8s cluster kept throwing: 
```
spec.pythonVersion in body must be of type string: "integer"
spec.pythonVersion in body should be one of [2 3]
```
Conflicting message - the list of possible values was listed as integers but it expects a string. 
**Changes:**
Simply make the list of possible values be string i.s.o. integers.
**Checks:**
Made the changes locally, applied the CRDs on a K8s cluster, and was able to deploy a SparkApplication resource successfully without getting any errors.
=> Enumerate string spec on Python version

examples/spark-pi.yaml, main.go, pkg/batchscheduler/volcano/volcano_scheduler.go, pkg/controller/sparkapplication/controller.go
This patch fixes some issues when integration with volcano scheduler.
1. Fix podgroup not block driver from creating.
2. Fix annotation not passed to driver&executor pods
3. Update spark jar version in yaml
4. remove unused argument in sparkoperator CLI.
Now there would be a repo which demonstrate the advantages that can bring to spark operator when configured with volcano [here](https://github.com/TommyLike/spark-operator-volcano-demo)
=> Fix integration issue with volcano

pkg/webhook/webhook.go
Fixes https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/628
=> Fix namespace selector when webhook failure disabled

pkg/apis/sparkoperator.k8s.io/v1beta2/types.go, pkg/apis/sparkoperator.k8s.io/v1beta2/zz_generated.deepcopy.go, pkg/webhook/patch.go, pkg/webhook/patch_test.go
Current support of environment variables is only for standard key-value through spark-submit.
K8S can support more complex envrionment variables like fetching values from other fields and secrets.
=> Full support of k8s environment variables for SparkApplication through webhook

pkg/controller/sparkapplication/job.go
when delete submit job, there are orphan pod that are not deleted, so we should set the delete PropagationPolicy when delete submit job.
/assign @liyinan926
=> fix bug when delete job, the job pod are not deleted

examples/spark-pi-schedule.yaml
Address #703 
`sparkVersion` is a required field in `ScheduledSparkApplication`. Without the field, user will see error like beflow
```
The ScheduledSparkApplication "spark-pi-scheduled" is invalid:
......
validation failure list:
spec.template.sparkVersion in body is required
```
=> Add sparkVersion in spark-pi-scheduled example

pkg/controller/sparkapplication/controller.go, pkg/controller/sparkapplication/sparkapp_util.go
(#715)
Current logic is wrong, because it sets Executor status to failed or completed in case if the pod is already terminated and Driver pod is still running. 
In fact, some executors can be finished and some executors still working on it's jobs. Current logic will set status of finished executors to failed only because there are still running executors, thus driver can't be in SucceedingState.
I think the solution is setting Completed/Failed to executors only after Application moved from RUNNING state.
=> Driver may still be in running state after executors has terminated

pkg/apis/sparkoperator.k8s.io/v1beta2/types.go, pkg/apis/sparkoperator.k8s.io/v1beta2/zz_generated.deepcopy.go, pkg/config/constants.go, pkg/controller/sparkapplication/submission.go
Part of #702 
Upstream Issue: 
https://issues.apache.org/jira/browse/SPARK-25515
https://github.com/apache/spark/pull/23136
Note: This is only working for spark-3.0.0. 
Test samples:
```
executor:
deleteOnTermination: false
cores: 1
instances: 2
memory: "512m"
```
spark-submit logs inside spark-operator
```
--conf spark.executor.cores=1 --conf spark.executor.memory=512m --conf spark.kubernetes.executor.deleteOnTermination=false --conf spark.kubernetes.executor.label.version=3.0.0-SNAPSHOT local:///opt/spark/examples/jars/spark-examples_2.12-3.0.0-SNAPSHOT.ja
```
```
kubectl get pods
NAME                                    READY   STATUS      RESTARTS   AGE
spark-pi-b672b16ef29c7918-exec-1        0/1     Completed   0          37s
spark-pi-b672b16ef29c7918-exec-2        0/1     Completed …
```
=> Add deleteOnTermination option to keep executor pods after a job is completed

.gitlab-ci.yml
This adds a builder for gitlab.com
Note that this depends on "git describe" to create the tag.
For this to work, you need to create some base tag with something like:
- git tag -a v0.0.1 -m 'Starting version v0.0.1'
After that, well-defined versions can be created by tagging with the
actual version number.
=> Add gitlab-ci.yml file

docs/user-guide.md, pkg/config/constants.go, pkg/controller/sparkapplication/sparkapp_util.go, pkg/controller/sparkapplication/submission.go, pkg/controller/sparkapplication/submission_test.go, pkg/webhook/patch.go, pkg/webhook/patch_test.go, sparkctl/cmd/s3.go
This PR helps to mount `HostPath` and `PersistentVolumeClaim` volume for Spark scratch space. Part of #702 
Upstream support was added here and this is included in Spark-3.0.0 (preview)
https://issues.apache.org/jira/browse/SPARK-28042
https://github.com/apache/spark/pull/24879/files
There're two different implementations I considered. 
1. Handle local dir differently and don't use webhook
2. Use webhook patch volume
`spark-local-dir-1` will be created automatically by spark before pods get patched if we don't specify volume for the scratch space. If we choose 2 option, we have to remove this volume and attach new volumes. What's more, SPARK_LOCAL_DIR env needs to be updated as well. I think the first option is more like a native way. 
Let me know if it makes sense and If there's more …
=> Add volumes support for Spark scratch space spark.local.dir

.gitlab-ci.yml, Dockerfile
Construct a build tag for the spark-operator with the SPARK_VERSION
appended.  Thus the operator-version_spark-version as in:
- v1beta2-8-g3e080b2_v2.4.4-12-g9f9ae44
This is an alternative, more minimal change than https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/723
But note that it assumes you are using a version of spark that is based on openjdk:8-jdk-slim as the current 2.4 branch for spark.
=> Use SPARK_REGISTRY and SPARK_VERSION for build

entrypoint.sh
Somehow this got lost in the updates.
The debian tini install puts it into /usr/bin/tini
=> Fix entrypoint.sh to /usr/bin/tini

docs/api-docs.md, pkg/apis/sparkoperator.k8s.io/v1beta2/types.go, pkg/config/constants.go, pkg/controller/sparkapplication/submission.go
The new field `.spec.driver.coreRequest` only works with Spark 3.0.
=> Added support for separate key for driver physical CPU request

pkg/webhook/patch.go, pkg/webhook/patch_test.go
when I use SparkApplication with subpath, for example:
```
apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
name: spark-sfs
spec:
arguments:
- "40000"
driver:
coreLimit: "1"
cores: 1
memory: 1536m
memoryOverhead: 512m
volumeMounts:
- mountPath: /package
name: cci-sfs-spark
subPath: spark-jar
- mountPath: /sfs
name: cci-sfs-spark
readOnly: false
executor:
coreLimit: 1000m
coreRequest: 1000m
instances: 1
memory: 1536m
memoryOverhead: 512m
volumeMounts:
- mountPath: /package
name: cci-sfs-spark
subPath: spark-jar
- mountPath: /sfs
name: cci-sfs-spark
readOnly: false
image: image:test
imagePullPolicy: Always
mainApplicationFile: local:///package/spark-examples_2.11-2.4.5-SNAPSHOT.jar
mainClass: org.apache.spark.examples.SparkPi
mode: cluster
restartPolicy: …
```
=> fix duplicate volume err when patch pod with subpath volume mount

docs/who-is-using.md
We are using the operator in production and glad to add the information to the adopters list.
Signed-off-by: Ce Gao <gaoce@caicloud.io>
=> feat: Add caicloud as a adopter

docs/user-guide.md, pkg/batchscheduler/interface/interface.go, pkg/batchscheduler/volcano/volcano_scheduler.go, pkg/controller/sparkapplication/controller.go
This PR fixed #826 by moving the place of applying defaults from the `onAdd` callback to the `submitSparkApplication` such that the defaults only get applied to a copy of the `SparkApplication` resource when submitting the application, instead of to the resource in the cache as received by `onAdd`. This avoids the changes of defaulting from being sent back to the API server and causing the application to be invalidated and resubmitted.
=> Fix for #826 and some refactoring

Dockerfile
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/845
=> golang:1.14.1-alpine is necessary related to issue 845

docs/quick-start-guide.md, main.go, pkg/controller/sparkapplication/controller.go, pkg/controller/sparkapplication/sparkapp_metrics.go, pkg/controller/sparkapplication/sparkapp_metrics_test.go, pkg/util/histogram_buckets.go, pkg/util/metrics.go
This PR adds job start latency metric. The job start latency is defined as the time since the sparkapp k8s object is created till when the job is in a running or terminal state. There are two metrics introduced in this change, one is `spark_app_start_latency_microseconds`, which is of Prometheus Summary type, and the other one is `spark_app_start_latency_seconds`, which is of Histogram type. The summary one is to give the user accurate latency values in different percentiles (e.g. 0.5, 0.9. 0.99), thus it's in microseconds. The histogram one is to give the user an option to configure the bucket boundaries, see how the job latency values fall into different histogram buckets, and thus can pick appropriate service job start latency SLA out of it, and thus it's in seconds for easier …
=> Add job start latency metrics and add namespace tag in metrics

docs/design.md, docs/developer-guide.md, docs/user-guide.md, sparkctl/README.md
Trivial fixes on typos, links and formats in several docs.
=> Fix typos and links in several docs

pkg/controller/scheduledsparkapplication/controller.go, pkg/controller/scheduledsparkapplication/controller_test.go
I ran into an issue where we had a scheduled job that we wanted to test a little earlier than the `nextRun`, so we applied changes with a modified schedule.  (e.g. `0 6 * * *` to `10 4 * * *` / 06:00 to 04:10 scheduled execution time) 
However, I observed at 04:30 that the scheduled spark application did not run and went to investigate why.  The next run was still set at `06:00`.  The only way I could get this issue rectified at the time was to delete and recreate the ScheduledSparkApplication. `replace` / `apply` operations did not affect the `nextRun` time at all from my experiments. 
Based off [this](https://kubernetes.slack.com/archives/CALBDHMTL/p1585877089005500?thread_ts=1585845895.005300&cid=CALBDHMTL), my understanding was that the next run is only set after each run, which …
=> ScheduledSparkApplications: NextRun should be recalculated if desired schedule changes

docs/quick-start-guide.md, pkg/controller/sparkapplication/controller.go, pkg/controller/sparkapplication/controller_test.go, pkg/controller/sparkapplication/sparkapp_metrics.go, pkg/controller/sparkapplication/sparkapp_metrics_test.go
Total SparkApplication count is the total number of SparkApplications that have been processed by the operator. This metric can be used to track how many SparkApplications the users have submitted to the K8s API server, and also can be used as denominator when computing job success rate, for example.
=> Add total SparkApplication count metric

pkg/controller/scheduledsparkapplication/controller.go, pkg/controller/scheduledsparkapplication/controller_test.go
Apparently if we don't explicitly set the namespace of the sparkApp, it will be "" and thus causing the unit test to fail.
=> Re-enable scheduled app unit test (TestSyncScheduledSparkApplication_Forbid)

pkg/apis/sparkoperator.k8s.io/v1beta2/types.go, pkg/controller/sparkapplication/controller.go, pkg/controller/sparkapplication/controller_test.go, pkg/controller/sparkapplication/sparkapp_util.go
Hello,
This PR is related to issue #841 
Following the discussion on this issue, i've implemented `option 2`
Specifically, I've introduced a new State Machine specific to the Driver that allow finer grain detection of application end when using sidecar containers
This is also compatible with  kubernetes sidecar implementation on version 1.18
I've also updated the tests to cover sidecar cases
PS: for the review the commit are  scoped
bfacfe9 is logic only
dbd2f21 is to fix and update tests
=> update code to fix error on termination time when using sidecar

pkg/config/constants.go, pkg/webhook/patch.go, pkg/webhook/patch_test.go
=> Fix for #868

spark-docker/Dockerfile
The current URL looks invalid:
```
Step 4/11 : ADD http://central.maven.org/maven2/com/google/guava/guava/23.0/guava-23.0.jar $SPARK_HOME/jars
ADD failed: failed to GET http://central.maven.org/maven2/com/google/guava/guava/23.0/guava-23.0.jar with status 503 Service Unavailable: <html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>ERROR: connection refused</title>
</head><body>
Failed to lookup host: central.maven.org
<br>
<p>Server is <a href="https://github.com/moby/vpnkit">moby/vpnkit</a></p>
</body>
</html>
```
=> Fix maven repo URL

docs/api-docs.md, manifest/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml, manifest/crds/sparkoperator.k8s.io_sparkapplications.yaml, pkg/apis/sparkoperator.k8s.io/v1beta2/types.go, pkg/controller/sparkapplication/sparkui_test.go
Spark 3.0 will support specifying a k8s service account for the executor pods. This CL prepares the operator to support that in the upcoming Spark 3.0.0 release.
=> Made field serviceAccount available for both driver and executors

docs/who-is-using.md
Hey there,
We are [Data Mechanics](https://www.datamechanics.co/), a managed Spark platform deployed on Kubernetes.
We use the spark-operator in the background; congrats for the great work by the way!
We have already contributed to the project (see #867) and hope to do more!
Cheers, Julien
=> Add Data Mechanics to who is using

pkg/config/constants.go, pkg/webhook/patch.go, pkg/webhook/patch_test.go
The issue is related to [#934](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/934). It allows to properly exposing the prometheus exporter to a SeriveMonitor or to Prometheus to scrape metrics. Up to now, we can only see the metrics generated locally but not exposed outside the pod running the JMX exporter.
=> Fixed issue (#934)

pkg/controller/sparkapplication/submission.go, pkg/controller/sparkapplication/submission_test.go
Populate Spark Application labels to Driver and Executors
The original discussion thread: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/905.
=> Populate Spark Application labels to Driver and Executors

docs/user-guide.md, main.go
Related to [#929](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/929).
As discussed in a previous PR. This allows to define some custom labels on which the operator will list and watch resources. For instance, this is useful if we want to run multiple instances of the operator.
=> support filtering resources on custom labels

pkg/controller/sparkapplication/job.go
@liyinan926 - This is critical for the image I'm using.
Should we allow propagation of the driver resources limits to the submit job too?
=> Higher spark-submit pod memory limit

manifest/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml, manifest/crds/sparkoperator.k8s.io_sparkapplications.yaml
Fixes https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/921.
=> Manually fix the CRD validation issue in k8s 1.18

.gitlab-ci.yml
Change the use of git describe to allow any tag including non-annotated
tags.
=> Allow any tag not just annotated tags in gitlab builds

README.md
The readme indicated that the mutating webhook was enabled by default
when spark-operator is installed via helm. This was inconsistent with
other documentation and the default value of `enableWebhook` in the
chart's values.yaml[1].
[1] https://github.com/helm/charts/blob/709c01f6e2fadb49d23cc80c62d1d5a169d0c938/incubator/sparkoperator/values.yaml#L26
=> Fix mutating webhook default state in README.md

docs/volcano-integration.md
This PR is just a tiny fix of a typo.
=> Fix a typo in docs/volcano-integration.md

docs/api-docs.md, pkg/apis/sparkoperator.k8s.io/v1beta2/types.go, pkg/apis/sparkoperator.k8s.io/v1beta2/zz_generated.deepcopy.go, pkg/webhook/patch.go, pkg/webhook/patch_test.go, pkg/webhook/webhook_test.go
This PR fixes typo in SparkPodSpec assuming that it's not intentional.
Signed-off-by: Abhilash Pallerlamudi <stp.abhi@gmail.com>
=> fixes typo in PodSecurityContext and SecurityContext in SparkPodSpec

docs/who-is-using.md
This PR aims to include Typeform as a Spark Operator user - Article [Spark Structured Streaming in K8s](https://medium.com/albert-franzi/spark-structured-streaming-in-k8s-with-argo-cd-de4942846161).
=> doc: Include Typeform as a K8s user

docs/user-guide.md, pkg/apis/sparkoperator.k8s.io/v1beta2/types.go, pkg/controller/sparkapplication/submission.go
- added support for packages, exclude-packages, and repositories
spark-submit parameters
- added these new parameters to the user guide documentation
=> Add support for spark-submit packages and repositories

docs/api-docs.md, pkg/webhook/patch.go, pkg/webhook/patch_test.go
See https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/821 .
Currently, the priority info is only at the `SparkApplication` resource level. This ensures the scheduling order while enqueueing the Spark applications but does not allow for job preemption, as the driver and executor pods all end up with the same priority (no priority actually - 0).
This PR is a straightforward solution: we simply propagate `spec.batchSchedulerOptions.priorityClassName`, if any, to `spec.priorityClassName` in the driver and executor pods (exactly as the priority is propagated to the `PodGroup` for Volcano).
I see no reason to implement it differently:
- The priority should apply to the Spark application as a whole, that means the driver and its executor pods
- As a consequence, the …
=> Propagate Spark app's priorityClassName to pods' spec

pkg/apis/sparkoperator.k8s.io/v1beta1/defaults.go, pkg/apis/sparkoperator.k8s.io/v1beta2/defaults.go, pkg/apis/sparkoperator.k8s.io/v1beta2/defaults_test.go
Only default Driver/Executor resources if not set both in Driver/Executor Spec and in SparkConf.
Ref: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1055 for details
=> Default Logic: Add SparkConf check

hack/gencerts.sh
when enable webhook for mutating admission control, occurred x.509 error from k8s api server.
in k8s api server error log
```
E1111 03:13:43.508139       1 dispatcher.go:171] failed calling webhook "webhook.sparkoperator.k8s.io": Post "https://spark-operator-webhook.spark-operator.svc:443/webhook?timeout=30s": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
```
in spark-operator error log
```
2020/11/10 11:05:56 http: TLS handshake error from xxx.xxx.xx.x:37154: remote error: tls: bad certificate
```
so, fixed `CN` from `${SERVICE}_ca` to operator service DNS name `${SERVICE}.${NAMESPACE}.svc`
=> Change certification CN to service domain

docs/who-is-using.md
This adds incrmntal to the list of users of spark-on-k8s-operator. We are using the operator in production on EKS to operate spark without the needs for Hadoop and using cloud filesystems directly (using s3a output committer).
Best
=> Add incrmntal to who-is-using.md

Makefile, charts/spark-operator-chart/Chart.yaml, charts/spark-operator-chart/README.md, charts/spark-operator-chart/README.md.gotmpl, charts/spark-operator-chart/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml, charts/spark-operator-chart/crds/sparkoperator.k8s.io_sparkapplications.yaml, charts/spark-operator-chart/templates/_helpers.tpl, charts/spark-operator-chart/templates/deployment.yaml, charts/spark-operator-chart/templates/rbac.yaml, charts/spark-operator-chart/templates/serviceaccount.yaml, charts/spark-operator-chart/templates/spark-rbac.yaml, charts/spark-operator-chart/templates/spark-serviceaccount.yaml, charts/spark-operator-chart/templates/webhook-cleanup-job.yaml, charts/spark-operator-chart/templates/webhook-init-job.yaml, charts/spark-operator-chart/templates/webhook-service.yaml, charts/spark-operator-chart/values.yaml
Related to https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1021
=> Add spark-operator chart

.github/workflows/release.yaml
To use this chart as a Helm 3 dependancy the chart needs to be released.
This PR adds a GitHub Action to do the following:
* Check for changes in the chart
* Lint the chart
* Create a kind cluster to test if there are changes
* Creates a release in the gh_pages branch
NOTE: A `gh-pages` branch will need to be created and [GitHub Pages enabled](https://guides.github.com/features/pages/) for this to complete. 
In my [test repo](https://github.com/jgardner04/spark-on-k8s-operator/tree/gh-pages) I created and orphaned branch and just added an index.html. the GitHub Action will then publish the index.yaml and the release as seen on that branch.
=> Add GitHub Action to Release Chart

pkg/batchscheduler/volcano/volcano_scheduler.go
when `BatchSchedulerOption` is nil, requested resource make the operator pod to error state with error message
```
Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
```
The attributes could be nil because volcano batch scheduler accepts empty scheduler queue in `BatchSchedulerOptions`.
=> Apply total resource when BatchSchedulerOption is not nil

pkg/controller/sparkapplication/controller.go, pkg/controller/sparkapplication/controller_test.go
the states of executors never going to COMPLETED although the spark application was completed.
```sh
$ sparkctl status spark-pi-volcano -n spark-job
application state:
+-----------+----------------+----------------+-------------------------+------------------+--------------------+-------------------+
|   STATE   | SUBMISSION AGE | COMPLETION AGE |       DRIVER POD        |    DRIVER UI     | SUBMISSIONATTEMPTS | EXECUTIONATTEMPTS |
+-----------+----------------+----------------+-------------------------+------------------+--------------------+-------------------+
| COMPLETED | 25m            | 25m            | spark-pi-volcano-driver | xx.xx.x.xxx:4040 |                  1 |                 1 |
+-----------+----------------+----------------+-------------------------+------------------+---- …
```
=> Update executor state after completed or failed app state

README.md
The URL provided in the current version of the readme causes a fail on `helm install` looking :
```bash
Error: failed to download "incubator/sparkoperator" (hint: running `helm repo update` may help)
```
Updating to this new URL make it works.
=> Update incubator URL

charts/spark-operator-chart/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml, charts/spark-operator-chart/crds/sparkoperator.k8s.io_sparkapplications.yaml, manifest/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml, manifest/crds/sparkoperator.k8s.io_sparkapplications.yaml
PR #1045 [1] appears to have accidentally reverted #986 [2] which added
defaults to the protocol field to work with versions of k8s 1.18+
This PR also draws on https://github.com/kudobuilder/operators/pull/297 [3]
[1] https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/1045
[2] https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/986
[3] https://github.com/kudobuilder/operators/pull/297
=> Fix crds to add defaults for k8s 1.18+

README.md, charts/spark-operator-chart/Chart.yaml, charts/spark-operator-chart/README.md, charts/spark-operator-chart/README.md.gotmpl, docs/quick-start-guide.md
=> Update docs with new helm instructions

docs/developer-guide.md, manifest/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml, manifest/crds/sparkoperator.k8s.io_sparkapplications.yaml, pkg/apis/sparkoperator.k8s.io/v1beta2/types.go, pkg/controller/sparkapplication/sparkapp_util.go, pkg/controller/sparkapplication/sparkui.go, pkg/controller/sparkapplication/sparkui_test.go
Fixes #1096. 
I also found that my controller-gen version behaved differently than the developer documentation described. I had to provide an additional configuration to use the v1beta1 CustomResourceDefinition version. I updated the docs and the generated CRDs accordingly.
=> Add configuration for SparkUI service type

pkg/batchscheduler/interface/interface.go, pkg/batchscheduler/volcano/volcano_scheduler.go, pkg/controller/sparkapplication/controller.go
Related to issue https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1062
The spark application injected with the volcano scheduler does not delete the pod group when the state of the spark application is changed to a completed or failed.
It can only be removed from the volcano queue by spark application deletion command or TTL timeout.
This will cause new pod groups to be scheduled to get stuck(pending) in the queue until spark application removed with ownerReference.
In my opinion, it would be better to remove the pod group when the spark application is changed to a completed or failed state.
=> Add scheduler func for clearing batch scheduling on completed

pkg/controller/sparkapplication/controller.go, pkg/controller/sparkapplication/controller_test.go
Hello,
This PR is related to issue #1076
Following the discussion on this issue, it seems that we can change the status of lost pods to `unknown` while the app is still `running`
Then once the driver pod is terminated, we fall back to the current implementation
=> update executor status if pod is lost while app is still running

charts/spark-operator-chart/README.md, charts/spark-operator-chart/templates/deployment.yaml, charts/spark-operator-chart/templates/prometheus-podmonitor.yaml, charts/spark-operator-chart/values.yaml, docs/quick-start-guide.md
* Supported Prometheus monitoring via pod monitor for the Spark operator's pod.
* Added Prometheus `metrics.portName` to use it for `podMonitor.podMetricsEndpoint` configuration, becuse `targetPort` has been deprecated by Prometheus.
=> Support Prometheus PodMonitor Deployment (#1106)

charts/spark-operator-chart/Chart.yaml
Upgraded the Chart version missed in [PR #1112](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/1112).
=> Upgrade the Chart version to 1.0.4

charts/spark-operator-chart/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml, charts/spark-operator-chart/crds/sparkoperator.k8s.io_sparkapplications.yaml, pkg/apis/sparkoperator.k8s.io/v1beta2/types.go, pkg/apis/sparkoperator.k8s.io/v1beta2/zz_generated.deepcopy.go, pkg/config/constants.go, pkg/webhook/patch.go, pkg/webhook/patch_test.go
`PodMonitor` is one of [prometheus operator](https://github.com/prometheus-operator/prometheus-operator) CRDs, and it collects metrics from pod selector.
For collecting, it requires port name of metrics
https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#podmetricsendpoint
port | Name of the pod port this endpoint refers to. Mutually exclusive with targetPort. | string
-- | -- | --
then, I have added metrics port name when mutating pod
it's example of `PodMonitor`
```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
name: spark-pod-monitor
labels:
foo: bar
spec:
selector:
matchLabels:
foo: bar
podMetricsEndpoints:
- port: metrics
interval: 10s
```
=> Add prometheus containr port name

charts/spark-operator-chart/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml, charts/spark-operator-chart/crds/sparkoperator.k8s.io_sparkapplications.yaml, docs/api-docs.md, pkg/apis/sparkoperator.k8s.io/v1beta2/types.go, pkg/apis/sparkoperator.k8s.io/v1beta2/zz_generated.deepcopy.go, pkg/webhook/patch.go, pkg/webhook/patch_test.go
Hello,
This PR addresses issue #981
Since I didn't know which CRDs are now actively maintained between the one in `charts/spark-operator-chart` and `manifest`
I've decided to prioritized the one in `charts`, don't hesitate to tell me if it's not the correct choice
=> add hostAliases for SparkPodSpec

charts/spark-operator-chart/Chart.yaml, charts/spark-operator-chart/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml, charts/spark-operator-chart/crds/sparkoperator.k8s.io_sparkapplications.yaml, charts/spark-operator-chart/templates/webhook-cleanup-job.yaml, charts/spark-operator-chart/values.yaml
This PR fixes some helm issues while deploying using argocd, namely a CRD which doesn't pass validation, and make the webhook-cleanup-job annotations configurable
This should close issue #1143
=> #1143 Helm issues while deploying using argocd

charts/spark-operator-chart/templates/serviceaccount.yaml
This enables users to install the chart using ArgoCD without setting special values.
This solves #1143 without requiring setting special undocumented values in values.yaml like the PR #1145 requires.
=> Helm: Put service account into pre-install hook.

go.mod
=> Fix go get issue with "unknown revision v0.0.0"

pkg/webhook/patch.go, pkg/webhook/patch_test.go
By default pods created by kube will have a priority of 0 set in their
spec, or the value of the PriorityClass acting as a `globalDefault`.
When using the `batchSchedulerOptions.priorityClassName` the spec was
mutated by adding the `priorityClassName` to the spec, but the
`priority` was left unchanged.
This caused an error 
```
the integer value of priority (0) must not be
provided in pod spec; priority admission controller computed X from
the given PriorityClass name.
```
(where X is the priority associated to the PrioritClass kube object)
The patcher now properly remove the existing priority when a
priorityClassName is applied, letting kube apply the correct priority to 
the executor and driver pods.
See https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/1054
=> fix: Remove priority from the spec when using priority class

sparkctl/cmd/create.go
Presently, anything specified in the sparkctl parameter `--upload-to` which is not parsed as part of the `host` component of a URL gets silently dropped and a hard-coded value is used instead:
`s3://test.bucket.io/a_prefix_for_my_app`  is parsed down to `test.bucket.io` and then `/spark-app-dependencies` gets added on the end.
This PR allows specifying a separate prefix component at the user's discretion with the --upload-prefix parameter:
```--upload-to test.bucket.io --upload-prefix a_prefix_for_my_app```
=> Allow custom bucket path

sparkctl/cmd/create.go
after merging https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/1207 and https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/1206 there are multiple prefixes for `p` causing build to fail, this PR removes `p` prefix for `s3-force-path-style`
=> remove multiple prefixes for 'p'

pkg/webhook/patch.go, pkg/webhook/patch_test.go
If there are more than 2 hostnames in `hostAliases` path, `spec/hostAliases` will only show the first and many last hostname. Like this:
```yaml
hostAliases:
- ip: "10.1.1.1"
hostnames:
- "hostname1"
- ip: "10.1.1.3"
hostnames:
- "hostname3"
- ip: "10.1.1.3"
hostnames:
- "hostname3"
```
Now fix this problem.
=> Fix the error of hostAliases when there are more than 2 hostnames

charts/spark-operator-chart/Chart.yaml, docs/api-docs.md, pkg/apis/sparkoperator.k8s.io/v1beta2/types.go, pkg/webhook/patch.go, pkg/webhook/patch_test.go
I'd like to expose other ports in my spark app, similar to what the spark-operator already has done to prometheus.
Its related to: 
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1202 
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1120
=> Add support to expose custom ports

pkg/webhook/patch.go, pkg/webhook/patch_test.go
Fixes #1233 
Starting at kubernetes 1.19, a PriorityClass can now define a
PreemptionPolicy. By default a pod will have a PreemptionPolicy set to
PreemptLowerPriority.
If the PriorityClass defines a different PreemptionPolicy, there will be
a conflict, so the patcher has to remove the PreemptionPolicy on the
pod. By default a PriorityClass will have a PreemptionPolicy set to
PreemptLowerPriority too, so it's safe to always remove it from the pod
when the priorityClassName is specified for the sparkapplication.
=> fix: remove preemptionPolicy when priority class name is used

README.md
Make it easier for new users to get to the slack channel.
=> Link to Kubernetes Slack

charts/spark-operator-chart/Chart.yaml, charts/spark-operator-chart/README.md, charts/spark-operator-chart/templates/deployment.yaml, charts/spark-operator-chart/templates/rbac.yaml, charts/spark-operator-chart/templates/spark-rbac.yaml, charts/spark-operator-chart/templates/webhook-cleanup-job.yaml, charts/spark-operator-chart/templates/webhook-init-job.yaml, charts/spark-operator-chart/values.yaml, hack/gencerts.sh
- webhook certificate name is tied to release names
- add flags to control the deployment of the Role and ClusterRole separately
=> Add support for blue/green deployments

pkg/webhook/patch.go
Introduced a bug in 3090b2abb80a6703a24423b76d144911a6891e2d. I
incorrectly assumed the preemptionPolicy was always set to a default on
pods, which is not the case in K8s versions prior to 1.19.
=> fix: do not remove preemptionPolicy in patcher when not present

docs/api-docs.md, manifest/crds/sparkoperator.k8s.io_sparkapplications.yaml, pkg/apis/sparkoperator.k8s.io/v1beta2/types.go, pkg/controller/sparkapplication/sparkui.go, pkg/controller/sparkapplication/sparkui_test.go
A proposal for solving https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1239 .
This PR makes it possible to specify the service port name for exposing the spark UI.
=> [#1239] Custom service port name for spark application UI

charts/spark-operator-chart/Chart.yaml, charts/spark-operator-chart/README.md, charts/spark-operator-chart/templates/deployment.yaml, charts/spark-operator-chart/values.yaml, main.go, pkg/controller/sparkapplication/controller.go, pkg/controller/sparkapplication/controller_test.go
This Pull request tries to provide users an option to disable UI service due to following reasons.
Spark Driver service contains the same port that is already exposed by UI service.
A global way to disable the service, as service is a limited resource in a Kubernetes cluster (Limit of 5000 per namespace and 10,000 per cluster).
Adding link to OpenShift maximums as I was not able to identify Kubernetes service maximum
This PR also closes #1031
=> Enable UI service flag for disabling UI service

charts/spark-operator-chart/Chart.yaml, charts/spark-operator-chart/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml, charts/spark-operator-chart/crds/sparkoperator.k8s.io_sparkapplications.yaml, docs/api-docs.md, manifest/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml, manifest/crds/sparkoperator.k8s.io_sparkapplications.yaml, pkg/apis/sparkoperator.k8s.io/v1beta2/types.go, pkg/controller/sparkapplication/sparkapp_util.go, pkg/controller/sparkapplication/sparkui.go, pkg/controller/sparkapplication/sparkui_test.go
Currently, there's no way to specify annotations on Spark UI services. One example of how this can be useful, is that we can add annotation on Spark UI services such that it can be ignored by Istio Pilot.
=> Allow user to specify service annotation on Spark UI service

.github/workflows/main.yaml, Makefile
Hello,
This PR address the issue of crds drift between chart/ and manifest/ encountered in #1262 
I've also delete redundant element in `.github/workflows/main.yaml`
This PR comes with an open question: 
Should we keep Travis-ci, since everything that it does is also check by GitHub workflow ?
=> add crds drift check between chart/ and manifest/

examples/spark-py-pi.yaml
spark 3.1.1 (specified in image) doesn't work with Python 2. 
This change updates pythonVersion from 2 to 3.
=> Update pythonVersion to fix example

pkg/controller/sparkapplication/controller.go, pkg/controller/sparkapplication/controller_test.go, pkg/controller/sparkapplication/sparkapp_util.go
Hello,
Since they were no traction on this issue: #1263
I've decided to implement solution 1 for executors
If i need to change anything do not hesitate
=> add failure context to recordExecutorEvent

charts/spark-operator-chart/values.yaml
Added comment that better describes the issue as in:
failed to run spark-submit for SparkApplication namespace/job-timestamp: signal: killed #1287
=> Explain "signal: kill" errors during submission

charts/spark-operator-chart/Chart.yaml, charts/spark-operator-chart/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml, charts/spark-operator-chart/crds/sparkoperator.k8s.io_sparkapplications.yaml, manifest/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml, manifest/crds/sparkoperator.k8s.io_sparkapplications.yaml
Hi,
I migrated both CRDs to v1 inspired on PR https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/1258 But editing the schema to fit the new api version.
I also added new columns to be shown with kubectl get.
$ kubectl get scheduledsparkapplication
```
NAME                   SCHEDULE      SUSPEND   LAST RUN   LAST RUN NAME                              AGE
snapshot-gen-feature   0 0 * * THU   false     6d11h      snapshot-gen-feature-1625097621612205851   8d
```
$ kubectl get sparkapplication
```
NAME                                       STATUS      ATTEMPTS   START                  FINISH                 AGE
snapshot-gen-feature-1625097621612205851   COMPLETED   1          2021-07-01T00:00:26Z   2021-07-01T01:08:15Z   6d11h
```
Note: I didn't find a way to make an operation …
=> Migrate CRDs from v1beta1 to v1. Add additionalPrinterColumns

charts/spark-operator-chart/Chart.yaml, charts/spark-operator-chart/README.md, charts/spark-operator-chart/templates/deployment.yaml, charts/spark-operator-chart/values.yaml
This adds the ability to define user labels on Spark operator pod. Main use case is integration with external logging solution. Please let me know if I should bump chart version in the PR or if you manage release cycle for the chart. Thanks
=> Add user defined pod labels

charts/spark-operator-chart/Chart.yaml, charts/spark-operator-chart/templates/serviceaccount.yaml
This PR relates to https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/1155 that added pre-install hook for Argo CD. Mentioned PR fixed the issue with the webhooks, however service account is deleted and recreated by the Argo on every sync. This effectively deletes service account token used by spark-operator pod and results in loosing RBAC permissions for operated Spark pods. New annotation with helm hook deletion policy will ensure that service account is not recreated.
=> Add hook deletion policy for spark-operator service account

pkg/controller/sparkapplication/controller.go, pkg/controller/sparkapplication/sparkapp_util.go
Hi,
Following testing on our side,
We've detected that the change I introduced on #1280 introduced NPE on executor failure on Spark3
This PR fix the executor on Spark3 and avoid NPE if we can't find the executor container
In case of NPE we show `Executor {{exec-name}} failed with ExitCode: -1, Reason: Unknown (Container not Found)`
=> fix NPE introduce on #1280

docs/quick-start-guide.md, docs/user-guide.md, pkg/config/constants.go, pkg/controller/sparkapplication/submission.go
This is a follow-up to #885, passes executor service account to spark.kubernetes.authenticate.executor.serviceAccountName
=> Add support for executor service account

pkg/controller/sparkapplication/controller.go, pkg/controller/sparkapplication/sparkapp_metrics.go
Decrease `running` metrics for the case of application deletion.
closes #1354
=> fix running metrics for application deletion

charts/spark-operator-chart/Chart.yaml, charts/spark-operator-chart/templates/rbac.yaml
This causes the issue: https://github.com/fluxcd/flux2/issues/2030
Tested with the following chart:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
name: spark-operator-development
namespace: development
spec:
chart:
spec:
chart: spark-operator
sourceRef:
kind: HelmRepository
name: enliven-systems
namespace: kube-system
version: 1.1.9
interval: 30m0s
install:
crds: CreateReplace
replace: true
remediation:
retries: -1
disableWaitForJobs: true
disableWait: true
timeout: "2m"
upgrade:
crds: CreateReplace
remediation:
retries: -1
disableWaitForJobs: true
uninstall:
timeout: "1m"
values:
image:
tag: v1beta2-1.2.3-3.1.1
pullPolicy: Always
webhook:
enable: true
namespaceSelector: "name=development"
sparkJobNamespace: development
resyncInterval: 10
metrics:
enable: …
```
=> `Role` and `RoleBinding` not installed for `webhook-init` in Helm `pre-hook`

charts/spark-operator-chart/Chart.yaml, charts/spark-operator-chart/templates/webhook-cleanup-job.yaml, charts/spark-operator-chart/templates/webhook-init-job.yaml
I think it makes sense to apply the same tolerations for spark-operator pod and webhook init/cleanup jobs.
Without tolerations support, this is an issue for users who have all nodes tainted.
=> Add custom toleration support for webhook jobs

charts/spark-operator-chart/Chart.yaml, charts/spark-operator-chart/README.md, charts/spark-operator-chart/templates/deployment.yaml, charts/spark-operator-chart/values.yaml, main.go, pkg/webhook/webhook.go
Webhook timeout by default is set to 30s (as we use AdmissionregistrationV1beta1) and sometimes that causes the request to fail when the number of pods in the cluster is huge.  We fix the webhook error by recreating the webhook manually with a lower timeout value (This does get modified when the operator pod restarts). 
We found kubernetes/kubernetes#71508, which talks about how the default client timeout is 30s, so if the webhooks have a timeout equal or greater, the client can give up before the apiserver has, which means the failurePolicy: ignore has no effect. 
This PR provides a way to set a default value for webhook timeout which allow the users to configure the timeout time based on their usage.
=> webhook timeout variable

pkg/webhook/webhook.go
When testing out the latest changes on k8s 1.22 I noticed that the pods were not getting mutated despite the webhook being invoked. 
When I checked the k8s logs I noticed an error message like the following
```
": expected webhook response of admission.k8s.io/v1, Kind=AdmissionReview, got /,
```
When I updated the operator to explicitly specify the Kind in TypeMeta the error went away and the modifications were applied to the pod.
=> Fixes an error that was preventing the pods from being mutated

.github/workflows/main.yaml, .github/workflows/release.yaml
I don't think any CI tool currently deploys the spark-operator to gcr.io, I think @liyinan926  has possibly been doing it manually.
This change moves to using the github container registry because the repository should be able to authenticate with github easier than requiring an administrator of this repository to do some manual steps.
it appears possible looking at this repository
https://github.com/GoogleCloudPlatform/gke-autoneg-controller/blame/master/.github/workflows/go.yml
=> use github container registry instead of gcr.io for releases

.github/workflows/main.yaml
It seems that https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/1418/files introduces a bug in the workflow, at step `Check changes in resources used in docker file` in job `build-spark-operator`:
```
- name: Check changes in resources used in docker file
run: |
DOCKERFILE_RESOURCES=$(cat Dockerfile | grep -P -o "COPY [a-zA-Z0-9].*? " | cut -c6-)
for resource in $DOCKERFILE_RESOURCES; do
if ! git diff  --quiet origin/master -- $resource; then
if ! git diff --quiet charts/spark-operator-chart/Chart.yaml | grep +appVersion; then
echo "resource used in gcr.io/spark-operator/spark-operator has changed in $resource, need to update the appVersion in charts/spark-operator-chart/Chart.yaml"
git diff origin/master -- $resource;
echo "failing the build... " && false
fi
fi
done
``` …
=> Fixes an issue with github action in job build-spark-operator

README.md, charts/spark-operator-chart/Chart.yaml, main.go, pkg/apis/sparkoperator.k8s.io/v1beta2/types.go, pkg/apis/sparkoperator.k8s.io/v1beta2/zz_generated.deepcopy.go, pkg/controller/sparkapplication/controller.go, pkg/controller/sparkapplication/controller_test.go, pkg/controller/sparkapplication/sparkapp_util.go, pkg/controller/sparkapplication/sparkui.go, pkg/controller/sparkapplication/sparkui_test.go, pkg/util/capabilities.go
Fixes https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1426.
This is a breaking change, meaning that on kubernetes versions older than 1.19 Ingress objects would fail to be created (everything else should still work as expected). It also defines the `pathType` statically as "ImplementationSpecific".
=> Kubernetes v1.22 extensions/v1beta1 API removal

.github/workflows/main.yaml, charts/spark-operator-chart/Chart.yaml, charts/spark-operator-chart/values.yaml, docs/api-docs.md
As the automated build system now pushes images to GitHub container registry, it makes sense to adjust the helm chart to use that as default instead of the old one.
=> Updated default registry to ghcr.io

.github/workflows/release.yaml, charts/spark-operator-chart/Chart.yaml, charts/spark-operator-chart/templates/deployment.yaml, charts/spark-operator-chart/values.yaml
It is needed to mount one or more volumes into spark operator pod  because of various reasons such as external ivy cache.
In this pr, it is supported to operator pod's volumes and volumeMounts in chart.
=> Add Operator volumes and volumeMounts in chart

charts/spark-operator-chart/Chart.yaml, pkg/controller/sparkapplication/controller.go
Under rare circumstances, a Spark driver pod could have been created despite the fact that spark submission attempt failed. The driver pod might not necessarily be running, it could be stuck in Pending state due to failure of creating the associated configmap, for example. In such situation, the current Spark operator would not attempt to resubmit the job, nor would the submission count attempt increase. As a result, the sparkapplication will be stuck in the submission failure state indefinitely.
This MR deletes the associated spark resource in case such situation arise, which will allow the spark operator to resubmit the job again.
=> Ensure that driver is deleted prior to sparkapplication resubmission

sparkctl/cmd/create.go, sparkctl/cmd/delete.go, sparkctl/cmd/log.go
This PR added the following features:
- New flags on `sparkctl create`
- `--logs`: watch SparkApplication logs until finished
- `--delete`: delete the SparkApplication if already exists
- Timeout on `sparkctl log` to wait the pod startup and produce a log
=> Implement --logs and --delete flags on 'sparkctl create' and a timeout on 'sparkctl log' to wait a pod startup

charts/spark-operator-chart/Chart.yaml, charts/spark-operator-chart/templates/rbac.yaml, charts/spark-operator-chart/templates/serviceaccount.yaml
In https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/1379#issuecomment-966284850, a breaking change was introduced. 
The result is that when I did a helm upgrade from 1.1.6 chart to a 1.1.10+ chart, the spark-operator ClusterRole and ClusterRoleBinding resources are deleted. also see: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1407
In this PR, I added pre-upgrade value to all 3 resources. Although it won't create the RBAC resources upon the 1st `helm upgrade` from the old chart(I think this is helm behavior), a second `helm upgrade` will apply the previously non-hook RBAC resources.
=> fix: add pre-upgrade hook to rbac resources

charts/spark-operator-chart/Chart.yaml, pkg/batchscheduler/volcano/volcano_scheduler.go
Volcano integration uses v1beta1 api version to check if podgroup CRD is present. However the apiextensions.k8s.io/v1beta1 API version for CRDs is no longer available in kubernetes 1.22+, apiextensions.k8s.io/v1 should be used instead.
=> Fix: use V1 api for CRDs for volcano integration

Makefile
This PR aims to rename unit tests to integration tests in Makefile#integration-test.
=> rename unit tests to integration tests in Makefile#integration-test

charts/spark-operator-chart/Chart.yaml, charts/spark-operator-chart/templates/webhook-cleanup-job.yaml, charts/spark-operator-chart/templates/webhook-init-job.yaml
Without `nodeSelector` being available, the init/cleanup pods will hang if k8s schedules them to run on ARM nodes (Graviton on EKS).
=> Webhook init and cleanup should respect nodeSelector

docs/user-guide.md, pkg/apis/sparkoperator.k8s.io/v1beta2/types.go, pkg/webhook/patch.go, pkg/webhook/patch_test.go
lifecycle rule for driver was added in this commit
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/commit/18572fa33bb0b99ed2f5ce24fa8be8f364c727f4
This PR add lifecycle to executor
=> add lifecycle to executor

charts/spark-operator-chart/templates/webhook-cleanup-job.yaml, charts/spark-operator-chart/templates/webhook-init-job.yaml
As per issue #1393 , this will ensure the tolerations block are within the if-block of the helm chart manifests for the Job resources.
Tested with `helm template` and tolerations set.
=> Fix #1393 : fix tolerations block in wrong segment for webhook jobs

charts/spark-operator-chart/Chart.yaml, charts/spark-operator-chart/templates/rbac.yaml
Added new RBAC permissions needed by default for leader election for the coordination/v1 API. 
Required after upgrade to golang:1.19.2.
In k8s.io/client-go@v0.25.3/tools/leaderelection/resourcelock/interface.go:166 `configMapsResourceLock` was removed and should be replaced by `ConfigMapsLeasesResourceLock`.
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1635
=> Added permissions for leader election #1635

charts/spark-operator-chart/README.md, charts/spark-operator-chart/templates/_helpers.tpl, charts/spark-operator-chart/templates/webhook-cleanup-job.yaml, charts/spark-operator-chart/templates/webhook-init-job.yaml, charts/spark-operator-chart/values.yaml
Added option to set extra common labels
Added options to set podlabels on the pods of the cleanup and init jobs
=> Extra helm chart labels

docs/who-is-using.md
Partly just to test the CLA check for my account, but also nice to be able to share or usage status.
=> Add Roblox to who-is

charts/spark-operator-chart/Chart.yaml, charts/spark-operator-chart/templates/deployment.yaml, charts/spark-operator-chart/values.yaml
Adding a sidecar to collect logs is a quite common requirement in a production environment.
=> Optional sidecars for operator pod

docs/quick-start-guide.md
This notes the controller intended to be used with the operator-managed ingress resources.
When setting up my own cluster I also tried https://docs.nginx.com/nginx-ingress-controller/ and https://kubernetes-sigs.github.io/aws-load-balancer-controller/ but the path format generated by the operator won't work with those.
=> Expand ingress docs a bit

charts/spark-operator-chart/templates/deployment.yaml, charts/spark-operator-chart/values.yaml
Useful to when env vars are used for auth when downloading `spark.archives` from S3.
=> Add envFrom to operator deployment

docs/quick-start-guide.md
As mentioned in the comment https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1708#issuecomment-1523442278, as well as several issues (e.g. https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1708, https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1725), the webhook default port change also affects AWS EKS clusters since March 2023. 
This PR is to update the docs to mention AWS EKS along with GKE for webhook port update.
=> Updating webhook docs to also mention eks

.github/workflows/main.yaml, charts/spark-operator-chart/Chart.yaml, charts/spark-operator-chart/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml, charts/spark-operator-chart/crds/sparkoperator.k8s.io_sparkapplications.yaml, docs/api-docs.md, manifest/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml, manifest/crds/sparkoperator.k8s.io_sparkapplications.yaml
* Added support for `seccompProfile` in Spark application CRD. It is necessary for Kubernetes Pod Security Standards Restricted profile.
https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted
* Aligned _manifest/crds_ with _charts/spark-operator-chart/crds_
* Fixed pre-commit jobs.
`build-helm-chart` and `integration-test` were failing with:
`Run manusa/actions-setup-minikube@v2.4.2
Error: Unsupported OS, action only works in Ubuntu 18 or 20`
=> Support `seccompProfile` in Spark application CRD and fix pre-commit jobs

charts/spark-operator-chart/README.md, charts/spark-operator-chart/templates/rbac.yaml, charts/spark-operator-chart/values.yaml
we run into issue that a helm sync operation performed by argocd will always recreate service account, rbac and  webhook
the way to mitigate this issue is to remove `pre-upgrade` from helm hook, but there is no way to add annotation on rbac
this PR addes annotation to rbac, so people can change their annotation on rbac and utilize last key on list takes priority feature to override the current annotation helm hook
=> Allowing optional annotation on rbac

docs/volcano-integration.md
Docs had old chart flags for enabling batch scheduler/webhook, so it was not working.
@liyinan926 can you help merge this?
=> Fix docs for Volcano integration

pkg/util/capabilities.go
Solution based in a similar issue fixed in helm: [helm/helm#6361](https://github.com/helm/helm/issues/6361)
To reproduce the problem, just deploy an `apiservice`
```bash
$ oc apply -f https://raw.githubusercontent.com/kubernetes/sample-apiserver/master/artifacts/example/apiservice.yaml
```
This gonna create an error in your cluster
```
$ oc api-resources > /dev/null
error: unable to retrieve the complete list of server APIs: wardle.example.com/v1alpha1: the server is currently unable to handle the request
```
After this, the Spark Operator `pod` will stop with the same error above.
This PR prevents this using the [IsGroupDiscoveryFailedError](https://pkg.go.dev/k8s.io/client-go@v1.5.2/1.5/discovery#IsGroupDiscoveryFailedError) method.
=> Handle invalid API resources in discovery

docs/who-is-using.md
Add Rokt to `who-is-using.md`. We're using the operator in production and are happy to see activity on the repo. We're likely to upstream some changes we've made internally
=> Add Rokt to who-is-using.md

charts/spark-operator-chart/templates/rbac.yaml, manifest/spark-operator-install/spark-operator-rbac.yaml, pkg/batchscheduler/volcano/volcano_scheduler.go
Fix issue #1723 
We fix some parts of code:
- pkg/batchscheduler/volcano/volcano_scheduler.go: to return error when appear on podGroup create.
- pkg/batchscheduler/volcano/volcano_scheduler.go and manifest/spark-operator-install/spark-operator-rbac.yaml to fix right on OCP.
It fix error on OCP
```
podgroups.scheduling.volcano.sh "spark-spark-test-pg" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>
```
=> fix: fix issue #1723 about spark-operator not working with volcano on OCP

charts/spark-operator-chart/README.md, charts/spark-operator-chart/templates/webhook-cleanup-job.yaml, charts/spark-operator-chart/templates/webhook-init-job.yaml, charts/spark-operator-chart/values.yaml
Problem: if you are using policies to ensure that all workloads in your cluster have resources limits & request (e.x. [gatekeeper](https://github.com/open-policy-agent/gatekeeper)) you need to be able to set those limits on all release workloads otherwise they simply will not be permitted to start with errors like:
`  Warning  FailedCreate  42s (x4 over 92s)  job-controller  Error creating: admission webhook "validation.gatekeeper.sh" denied the request: [requiredresources] container <main> does not have <{"cpu", "memory"}> limits defined
[requiredresources] container <main> does not have <{"cpu", "memory"}> requests defined
`
Solution: allow to set resources for webhook jobs. Related issues: #1300, #1429.
Tested cases:
- `helm template charts/spark-operator-chart/`  - ok
- `helm template …
=> Allow to set webhook job resource limits (#1429,#1300)

charts/spark-operator-chart/Chart.yaml, charts/spark-operator-chart/templates/rbac.yaml
Add PVC permission to Operator role, so that Spark Operator able to create Driver pod with PVC by follow spark configs:
```
spark.kubernetes.driver.volumes.persistentVolumeClaim.checkpointpvc.options.claimName: "driver"
spark.kubernetes.driver.volumes.persistentVolumeClaim.checkpointpvc.options.storageClass: "gp2"
spark.kubernetes.driver.volumes.persistentVolumeClaim.checkpointpvc.options.sizeLimit: "50Gi"
spark.kubernetes.driver.volumes.persistentVolumeClaim.checkpointpvc.mount.path: "/data"
spark.kubernetes.driver.volumes.persistentVolumeClaim.checkpointpvc.mount.readOnly: "false"
```
https://spark.apache.org/docs/latest/running-on-kubernetes.html#using-kubernetes-volumes
=> Add PVC permission to Operator role

docs/user-guide.md
I found mismatched quotes from user-guide.md merged from PR https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/1524
=> remove unmatched quotes from user-guide.md

sparkctl/cmd/event.go
This PR fixes a context leak bug in your code.
While triaging your project, our bug fixing tool generated the following message-
> In file: [event.go](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/sparkctl/cmd/event.go#L157), method `context.WithTimeout` is called where the returned cancel function is ignored. It is suggested that the returned cancel function shouldn't be ignored.
In the line below, a context is created using the `WithTimeout` method, where the returned `cancelFunc` handler is ignored. 
```
ctx, _ = context.WithTimeout(ctx, watchExpire)
```
I have introduced the `cancel` handler and deferred it so that once the method `Run()` completes execution, it can be safely cancelled.
This work is done by the security researchers from OpenRefactory and is …
=> BUGFIX: Added cancel method to fix context leak

charts/spark-operator-chart/Chart.yaml, charts/spark-operator-chart/templates/rbac.yaml
While trying to run spark operator with Spark 3.5.0, I noticed the following errors:
```
Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. services "spark-pi-test-run-1-72fa8a8c0fd5639e-driver-svc" is forbidden: User "system:serviceaccount:spark:sparkoperator-spark-spark-operator" cannot patch resource "services" in API group "" in the namespace "spark-test-apps".
at io.fabric8.kubernetes.client.KubernetesClientException.copyAsCause(KubernetesClientException.java:238)
at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:518)
at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:535)
at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.ha …
```
=> Chart: add patch permissions for spark operator SA to support spark 3.5.0

.github/workflows/main.yaml, .github/workflows/release.yaml, charts/spark-operator-chart/Chart.yaml, charts/spark-operator-chart/README.md, charts/spark-operator-chart/templates/deployment.yaml, charts/spark-operator-chart/templates/spark-rbac.yaml, charts/spark-operator-chart/templates/spark-serviceaccount.yaml, charts/spark-operator-chart/values.yaml
replaced sparkJobNamespace with sparkJobNamespaces, added creation of spark role, serviceaccount and rolebinding for every spark job namespace
=> support multiple namespaces

charts/spark-operator-chart/Chart.yaml, charts/spark-operator-chart/README.md, charts/spark-operator-chart/templates/deployment.yaml, charts/spark-operator-chart/templates/webhook-service.yaml, charts/spark-operator-chart/values.yaml
Adds a missing port declaration for the container port serving the webhook to the helm chart. Bumps the chart version for this fix. 
Notice that this port _is correctly declared_ in the kustomize patches, it's just the helm chart that didn't expose this. 
Here's the port being declared for the kustomize manifests that enable the webhook: 
https://github.com/kubeflow/spark-operator/blob/252eddd2fac294de0fff6dc9e14e23574221f960/manifest/spark-operator-with-webhook.yaml#L51-L52
But here, the helm chart only creates a port for metrics, with no condition to add a port when `.Values.webhook.enable` is true 
https://github.com/kubeflow/spark-operator/blob/252eddd2fac294de0fff6dc9e14e23574221f960/charts/spark-operator-chart/templates/deployment.yaml#L49-L53
Closes: #1962
=> fix: add containerPort declaration for webhook in helm chart

.github/workflows/release.yaml, charts/spark-operator-chart/Chart.yaml
moved chart publishing to a separate job which runs after publish image is skipped or succeeded
=> publish chart independently, incremented both chart and image versions to trigger build of both

.github/workflows/release.yaml, charts/spark-operator-chart/Chart.yaml, charts/spark-operator-chart/README.md
now docker images are published with 'preview' tag. changed it to a app version from Chart.yaml
=> fixed docker image tag and updated chart docs

Makefile, charts/spark-operator-chart/.helmignore, charts/spark-operator-chart/Chart.yaml, charts/spark-operator-chart/README.md, charts/spark-operator-chart/templates/deployment.yaml, charts/spark-operator-chart/templates/rbac.yaml, charts/spark-operator-chart/templates/spark-serviceaccount.yaml, charts/spark-operator-chart/tests/deployment_test.yaml, charts/spark-operator-chart/tests/rbac_test.yaml, charts/spark-operator-chart/tests/serviceaccount_test.yaml, charts/spark-operator-chart/tests/spark-rbac_test.yaml, charts/spark-operator-chart/tests/spark-serviceaccount_test.yaml, charts/spark-operator-chart/tests/webhook-service_test.yaml, docs/developer-guide.md
- Add some helm chart unit tests
- Close #1966 
- Update developer guide about how to setup git pre-commit hooks and developing with helm chart
=> Add some helm chart unit tests and fix spark service account render failure when extra annotations are specified

.github/workflows/release.yaml
- Publishing Helm chart is being skipped due to the needs condition on `publish-image` 
- Removed the needs condition on publishing helm chart job
#1994
=> fix: Removed `publish-image` dependency on publishing the helm chart

charts/spark-operator-chart/Chart.yaml, charts/spark-operator-chart/README.md, docs/user-guide.md, pkg/controller/sparkapplication/submission.go, pkg/controller/sparkapplication/submission_test.go
* Support the `sizeLimit` field for `emptyDir` volume types that are prefixed with `spark-local-dir-...`
* If creating an `emptyDir` volume without a `spark-local-dir-...` prefix, the webhook will patch the appropriate volume onto the pod spec, but Spark will still create an `emptyDir` volume anyway https://github.com/apache/spark/blob/fd3f70c74ba63a0209a4a48a387048ef40380e0f/resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/k8s/features/LocalDirsFeatureStep.scala#L38-L40
* However if using a `spark-local-dir-...`, which the operator doesn't consider in the webhook and instead supplies at submission time, the sizeLimit is not carried through to the resulting volume in K8s
* It may be desirable to set a …
=> Add emptyDir sizeLimit support for local dirs

README.md, docs/quick-start-guide.md
In https://github.com/kubeflow/spark-operator/pull/1955 the use of `sparkJobNamespace` was replaced with `sparkJobNamespaces`. However the [README.md](https://github.com/kubeflow/spark-operator/blob/master/README.md) and the [Quick Start Guide](https://github.com/kubeflow/spark-operator/blob/master/docs/quick-start-guide.md) still show the use of the old Helm value.
- Update docs with the new Helm value
- To the best of my knowledge there are two ways to set a list value of a Helm Chart: `--set "sparkJobNamespaces={default}"` and `--set sparkJobNamespaces[0]=default` (for personal preference I went with the first one)
- The `About the Spark Job Namespace` section in the quick start guide was referencing …
=> Update Spark Job Namespace docs

examples/spark-py-pi.yaml
Confusing warning in the Python example that Python support is experimental. Python support seems stable in current versions, correct?
Remove outdated (?) warning in the pyspark example that Python support is experimental. (This was written 6 years ago)
This is confusing if no longer correct.
=> Remove outdated PySpark experimental warning in example

charts/spark-operator-chart/Chart.yaml, charts/spark-operator-chart/README.md, pkg/apis/sparkoperator.k8s.io/v1beta2/defaults.go, pkg/apis/sparkoperator.k8s.io/v1beta2/defaults_test.go
Fixes a bug with dynamic allocation forcing the executor count to be 1 even when minExecutors is set to 0
Resolves otherwise unexpected behavior where the value of minExecutors was not fully respected.
=> Fixes a bug with dynamic allocation forcing the executor count to be 1 even when minExecutors is set to 0

charts/spark-operator-chart/Chart.yaml, charts/spark-operator-chart/README.md, charts/spark-operator-chart/templates/deployment.yaml
PR #1983 made leader election resourcelock to work based on POD_NAME identity(see the changes in `main.go` file). However POD_NAME environment variable is not being passed to spark operator pod. This results in the error described in #1987.
Resolves #1987 .
This PR adds POD_NAME environment variable to spark operator pods when leader_election is required.
=> Chart: add POD_NAME env for leader election

.github/workflows/main.yaml
Following on from discussion [here](https://github.com/kubeflow/spark-operator/pull/2058#issuecomment-2166301679), this PR intends to update the `minikube` version in CI to the latest. This is to fix an issue on the current version of minikube in [use](https://github.com/kubeflow/spark-operator/actions/runs/9506313545/job/26203210211?pr=2058).
- Update `minikube` action to latest version - `2.11.0`, as well as the minikube version.
Before submitting your PR, please …
=> Update minikube version in CI

.github/workflows/main.yaml, charts/spark-operator-chart/Chart.yaml, charts/spark-operator-chart/README.md, charts/spark-operator-chart/templates/deployment.yaml, charts/spark-operator-chart/values.yaml, pkg/webhook/webhook.go, pkg/webhook/webhook_test.go
When the jobs are run for the `spark-operator` in the same namespace in which the operator resides, the operator will attempt to mutate itself. 
- This PR adds support for specifying an `objectSelector` on the `MutatingWebhookConfiguration` so as a user can specify _what_ pods matching a given set of labels the operator can mutate. See also related [issue](https://github.com/kubeflow/spark-operator/issues/1608) requesting this.
- ~This PR also updates the `minikube` CI action to the latest release.~ This has been moved to this …
=> Support objectSelector on mutating webhook

README.md
This PR is for the change proposed in https://github.com/kubeflow/spark-operator/issues/2061
The PR aims at providing the new CNCF slack Channel details so that new users can go to new slack channel instead of old slack channel which is going to be archived soon.  See details here (https://github.com/kubeflow/spark-operator/issues/2061)
- Update slack channel to CNCF Slack channel
Users are currentl joining the old slack channel instead of the new one
=> Modified README.MD as per changes discussed on https://github.com/kubeflow/spark-operator/pull/2062

.github/workflows/stale.yaml
Add workflow for closing staled issues and PRs:
- The issues/PRs will be marked as stale for 60 days with no activity and will be closed after 30 days with no activity.
=> Add workflow for closing stale issues and PRs

.github/workflows/stale.yaml
I updated the stale bot settings which allows us to mark issues and PRs with `/lifecycle frozen` label that we don't want to close, like here: https://github.com/kubeflow/training-operator/issues/2032#issuecomment-2194398776
Prow bot automatically adds this label to the issues/PRs.
I used the same settings as we use for other projects:
- https://github.com/kubeflow/training-operator/blob/master/.github/workflows/stale.yaml
- https://github.com/kubeflow/katib/blob/master/.github/workflows/stale.yaml
/assign @vara-bonthu @yuchaoran2011 @ChenYi015 …
=> Update Stale bot settings

.github/workflows/integration.yaml
When integration test workflow is triggered by push event, the CI failed https://github.com/kubeflow/spark-operator/actions/runs/10198309429/job/28212951826#logs.  The `origin/ref/heads/` prefix of branch name should be stripped.
**Proposed changes**:
- Replace `github.ref` with `github.ref_name`
- Skip check helm docs and helm install CI if helm charts does not change
=> Fix broken integration test CI

.github/workflows/integration.yaml
The integration test CI on the release branch [failed](https://github.com/kubeflow/spark-operator/actions/runs/10209326157/job/28247176105?pr=2110)  due to missed `BRANCH` environment variable.
- Add `BRANCH` environment variable
=> Fix CI: environment variable BRANCH is missed

.github/workflows/stale.yaml
I increased frequency for Stale bot (run every 2 hours) and number of operations per run.
This should help us to faster process 517 open issues and PRs.
/assign @vara-bonthu @yuchaoran2011 @ChenYi015
=> Increase frequency for Stale bot

cmd/operator/controller/start.go, cmd/operator/webhook/start.go
- Add default values for namespaces to match usage descriptions
- Remove incorrect cache settings
- [ √ ] Bugfix (non-breaking change which fixes an issue)
- [ √ ] I have conducted a self-review of my own code.
- [ √ ] Existing unit tests pass locally with my changes.
=> fix: Add default values for namespaces to match usage descriptions 

charts/spark-operator-chart/templates/spark/_helpers.tpl, charts/spark-operator-chart/templates/spark/rbac.yaml, charts/spark-operator-chart/tests/spark/rbac_test.yaml
Close #2134 
- Fix roleRef in Spark role binding
`roleRef` in Spark role binding did not refer to the correct Spark role name. Thus, driver pod failed to create executor pods:
```
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://kubernetes.default.svc/api/v1/namespaces/bladerunner/pods/xxx-driver. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods "xxx" is forbidden: User "system:serviceaccount:test:spark-sa" cannot get resource "pods" in API group "" in the namespace "test": RBAC: role.rbac.authorization.k8s.io "spark-sa" not found.
```
=> Fix: Spark role binding did not render properly when setting spark service account name

charts/spark-operator-chart/README.md, charts/spark-operator-chart/templates/webhook/deployment.yaml, charts/spark-operator-chart/templates/webhook/mutatingwebhookconfiguration.yaml, charts/spark-operator-chart/templates/webhook/poddisruptionbudget.yaml, charts/spark-operator-chart/templates/webhook/rbac.yaml, charts/spark-operator-chart/templates/webhook/service.yaml, charts/spark-operator-chart/templates/webhook/serviceaccount.yaml, charts/spark-operator-chart/templates/webhook/validatingwebhookconfiguration.yaml, charts/spark-operator-chart/tests/webhook/deployment_test.yaml, charts/spark-operator-chart/tests/webhook/mutatingwebhookconfiguration_test.yaml, charts/spark-operator-chart/tests/webhook/poddisruptionbudget_test.yaml, charts/spark-operator-chart/tests/webhook/service_test.yaml, charts/spark-operator-chart/tests/webhook/validatingwebhookconfiguration_test.yaml, charts/spark-operator-chart/values.yaml
Close #2137.
- Reintroduce option `webhook.enable`
- The webhook is enabled by default, but users can choose to disable the webhook server when webhooks are forbidden in K8s
=> Reintroduce option webhook.enable

charts/spark-operator-chart/README.md, charts/spark-operator-chart/templates/controller/deployment.yaml, charts/spark-operator-chart/tests/controller/deployment_test.yaml, charts/spark-operator-chart/values.yaml, cmd/operator/controller/start.go, internal/controller/sparkapplication/controller.go
Allow users to specify a default batch scheduler for all applications on the cluster. This allows all applications to benefit from batch scheduling features e.g. gang scheduling without needing to change the spec of all applications.
Completes the second task in https://github.com/kubeflow/spark-operator/issues/2098
=> Add default batch scheduler argument

charts/spark-operator-chart/templates/controller/deployment.yaml, charts/spark-operator-chart/templates/webhook/deployment.yaml, charts/spark-operator-chart/tests/controller/deployment_test.yaml, charts/spark-operator-chart/tests/webhook/deployment_test.yaml
- The helm should set controller/webook replicas to `0` if `[controller|webhook].replicas` is `0`
The `replicas` field of the deployment is missing when setting `[controller|webhook].replicas` to `0`, so the replicas will default to `1`.
=> fix: unable to set controller/webhook replicas to zero

charts/spark-operator-chart/templates/controller/deployment.yaml, charts/spark-operator-chart/templates/spark/rbac.yaml, charts/spark-operator-chart/templates/spark/serviceaccount.yaml, charts/spark-operator-chart/templates/webhook/deployment.yaml, charts/spark-operator-chart/templates/webhook/mutatingwebhookconfiguration.yaml, charts/spark-operator-chart/templates/webhook/validatingwebhookconfiguration.yaml, charts/spark-operator-chart/tests/controller/deployment_test.yaml, charts/spark-operator-chart/tests/spark/serviceaccount_test.yaml, charts/spark-operator-chart/tests/webhook/deployment_test.yaml, charts/spark-operator-chart/tests/webhook/mutatingwebhookconfiguration_test.yaml, charts/spark-operator-chart/tests/webhook/validatingwebhookconfiguration_test.yaml, cmd/operator/controller/start.go, cmd/operator/webhook/start.go, internal/controller/scheduledsparkapplication/event_filter.go, internal/controller/sparkapplication/event_filter.go
Add support for setting `spark.jobNamespaces` to all namespaces (`""`).
- controller/webhook should watch all namespaces if `spark.jobNamespaces` is empty list or contains `""`
- should not create spark service account and rbac resources for empty namespace
- mutating/validating webhook configurations should not add `namespaceSelector` when `spark.jobNamespaces` is empty list or contains `""`
1. If we want to watch all namespaces, then we can install the spark operator as follows:
```bash
helm install spark-operator charts/spark-operator-chart \
--create-namespace \
--namespace spark-operator \
--set 'spark.jobNamespaces={}'
```
but this will not create rbac resources for spark in any namespaces.
2. If we want to watch all namespaces and also create rbac resources for spark in namespace …
=> Adding support for setting spark job namespaces to all namespaces

charts/spark-operator-chart/README.md, charts/spark-operator-chart/templates/controller/deployment.yaml, charts/spark-operator-chart/templates/controller/rbac.yaml, charts/spark-operator-chart/values.yaml, cmd/operator/controller/start.go, examples/spark-pi-kube-scheduler.yaml, go.mod, go.sum, internal/controller/sparkapplication/controller.go, internal/scheduler/kubescheduler/scheduler.go, internal/scheduler/kubescheduler/util.go
Close #1943
- Support extended kube-scheduler as batch scheduler by using [scheduler-plugins](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/pkg/coscheduling/README.md).
=> Support extended kube-scheduler as batch scheduler

.github/workflows/integration.yaml, Makefile, charts/spark-operator-chart/ci/kind-config.yaml, test/e2e/suit_test.go
The existing end-to-end tests haven't been run for what seems like quite a long time. It's important that new or existing end-to-end tests are run in CI as a required check for PRs to be merged to ensure that bugs aren't introduced.
**Changes:**
- Run all jobs under `integration.yaml` on `ubuntu-latest`
- Create a new `e2e-test` job to replace the existing `integration-test` job that spins up a Kubernetes cluster using Kind, builds and loads the image to the cluster, then runs the existing four e2e tests
Closes https://github.com/kubeflow/spark-operator/issues/1416
Prerequisite work before adding an end to end test for the Yunikorn batch scheduler integration for https://github.com/kubeflow/spark-operator/issues/2098
Before …
=> Run e2e tests on Kind

internal/scheduler/yunikorn/scheduler.go, internal/scheduler/yunikorn/scheduler_test.go
If an application's `batchScheduler` is set to `yunikorn`, set the `schedulerName` field of pods to `yunikorn` to ensure they are scheduler by Yunikorn if it is installed with the admissions controller disabled
```bash
helm install yunikorn yunikorn/yunikorn --namespace yunikorn --create-namespace --set embedAdmissionController=false
kubectl apply -f examples/spark-pi-yunikorn.yaml
```
=> Set schedulerName to Yunikorn

charts/spark-operator-chart/templates/controller/_helpers.tpl, charts/spark-operator-chart/templates/controller/rbac.yaml, charts/spark-operator-chart/templates/controller/serviceaccount.yaml, charts/spark-operator-chart/templates/webhook/_helpers.tpl, charts/spark-operator-chart/templates/webhook/rbac.yaml, charts/spark-operator-chart/templates/webhook/serviceaccount.yaml, charts/spark-operator-chart/tests/webhook/rbac_test.yaml
- To enhance RBAC security, when spark operator is not watching all namespaces, then it is better to create role and rolebinding for controller/webhook in every spark job namespace and remove the associated rbac rules from clusterrole.
- [] Documentation update
Enhance spark operator RBAC security.
=> Create role and rolebinding for controller/webhook in every spark job namespace if not watching all namespaces

test/e2e/sparkapplication_test.go, test/e2e/suit_test.go
- Wait for the webhooks to be ready in e2e test CI
The [e2e CI](https://github.com/kubeflow/spark-operator/actions/runs/10678444394/job/29595500565) occasionally failed due to webhook not ready. 
=> Fix: e2e test failes due to webhook not ready

Dockerfile, go.mod
Upgrade Golang from 1.22.5 to 1.23.1
=> Upgrade to Go 1.23.1

Dockerfile, config/samples/v1beta1_sparkapplication.yaml, config/samples/v1beta2_scheduledsparkapplication.yaml, config/samples/v1beta2_sparkapplication.yaml, examples/spark-pi-configmap.yaml, examples/spark-pi-custom-resource.yaml, examples/spark-pi-dynamic-allocation.yaml, examples/spark-pi-kube-scheduler.yaml, examples/spark-pi-python.yaml, examples/spark-pi-scheduled.yaml, examples/spark-pi-volcano.yaml, examples/spark-pi-yunikorn.yaml, examples/spark-pi.yaml
Upgrade from Spark 3.5.0 to Spark 3.5.2 in both the Dockerfile and examples.
* The example JAR is present on the 3.5.2 images and `examples/spark-pi-python.yaml` ran on Kind. 
* There is nothing in particular I can see in the Spark 3.5.1 or 3.5.2 changelogs that would impact how the operator works (there is https://github.com/apache/spark/pull/43536 but this flag isn't used when constructing the `spark-submit` command internally)
=> Upgrade to Spark 3.5.2

.github/workflows/integration.yaml, examples/spark-pi-configmap.yaml, examples/spark-pi-custom-resource.yaml, examples/spark-pi-dynamic-allocation.yaml, examples/spark-pi-kube-scheduler.yaml, examples/spark-pi-prometheus.yaml, examples/spark-pi-python.yaml, examples/spark-pi-scheduled.yaml, examples/spark-pi-volcano.yaml, examples/spark-pi-yunikorn.yaml, examples/spark-pi.yaml, test/e2e/sparkapplication_test.go, test/e2e/suit_test.go
- Remove duplicate operator image build tasks in integration test
- Add time sleep buffer to ensure that webhooks are ready before running the e2e tests
- Check whether volumes are mounted in e2e tests
- Check whether resource requests and limits are set in e2e tests
- Remove the `coreLimit` field from all example spark applications except for `spark-pi-custom-resource.yaml`. For that, added `coreRequest` and `coreLimit` fields to it.
The e2e tests of the recent PRs still failed due to the webhook not ready, even after checking the CA bundle and webhook service enpoints.
=> Update e2e tests

internal/webhook/sparkpod_defaulter.go
Close #2162
- Update Spark pod defaulter to correctly filter out spark pods when settings spark job namespaces to namespaceAll (`""`)
=> fix: webhook not working when settings spark job namespaces to empty

internal/controller/sparkapplication/driveringress.go
Added the missing 'name' argument.
```go
2024-09-13T08:13:11.918Z    DPANIC    sparkapplication/driveringress.go:215    odd number of arguments passed as key-value pairs for logging    {"ignored key": "a-050b405cdef244e597949ba281f33579-ui-ingress"}
github.com/kubeflow/spark-operator/internal/controller/sparkapplication.(*Reconciler).createDriverIngressLegacy
/workspace/internal/controller/sparkapplication/driveringress.go:215
github.com/kubeflow/spark-operator/internal/controller/sparkapplication.(*Reconciler).createWebUIIngress
/workspace/internal/controller/sparkapplication/web_ui.go:54
github.com/kubeflow/spark-operator/internal/controller/sparkapplication.(*Reconciler).submitSparkApplication
/workspace/internal/controller/sparkapplication/controller.go:697 …
```
=> fix: The logger had an odd number of arguments, making it panic

ADOPTERS.md
Following discussion on https://github.com/kubeflow/spark-operator/pull/2164
I've decided to open a new PR for the replacement of datamechanics.co (shutdown since May) by spot.io following the acquisition in 2021
=> replace datamechanics -> spot.io as adopter (acquisition)

examples/spark-pi-prometheus.yaml, spark-docker/Dockerfile
#2012 Problem resolved.
"gcr.io/spark-operator/spark:v3.1.1" is used as the base image, but the image is a legacy image and can no longer be used.
So I changed it to spark:3.5.2.
I tested it locally and it worked fine.
- Prometheus-related content has been upgraded to Spark version 3.5.2.
=> Upgrade to Spark 3.5.2(#2012)

charts/spark-operator-chart/README.md, charts/spark-operator-chart/templates/controller/_helpers.tpl, charts/spark-operator-chart/templates/controller/deployment.yaml, charts/spark-operator-chart/templates/controller/service.yaml, charts/spark-operator-chart/tests/controller/deployment_test.yaml, charts/spark-operator-chart/tests/controller/service_test.yaml, charts/spark-operator-chart/values.yaml, cmd/operator/controller/start.go
This PR aim to allow access to the pprof server expose by the controller-runtime manager
This could help pinpoint issue with profiling while also opening the way for [Profile-guided optimization](https://go.dev/blog/pgo) build of the operator
- add `--pprof-bind-address` option to the controller
- add the associated values to the helm chart
=> Feature: Add pprof endpoint

Makefile
Fix `make kind-delete-custer` to only delete the cluster context instead of the entire kube config
I deleted my entire kubeconfig while debugging E2E tests for another PR 🙃 
=> fix the make kind-delete-custer to avoid accidental kubeconfig deletion

internal/scheduler/yunikorn/resourceusage/memory.go, internal/scheduler/yunikorn/scheduler_test.go
Account for `spark.executor.pyspark.memory` when calculating executor memory requests when gang scheduling with Yunikorn.
Fixes https://github.com/kubeflow/spark-operator/issues/2176
=> Account for spark.executor.pyspark.memory in Yunikorn gang scheduling

examples/spark-pi-ttl.yaml, internal/controller/sparkapplication/controller.go, pkg/util/sparkapplication.go
Close #1761 .
- When TTL is set, Spark application should be cleaned up as expected.
- Add TTL example `spark-pi-ttl.yaml`.
=> Fix: spark application does not respect time to live seconds

Dockerfile, cmd/operator/webhook/start.go
Reduce the permission of the docker image by making it non-root (like the spark image it's build from)
- Re-enable go mod caching while building the image
- Make the image use the USER define in the base spark-image (UID: 185, NAME: spark)
- Use `setcap` on the binary to keep the ability to mount port <1024 (useful for people mounting webhook on 443)
If we aim to increase security of the project, making the image non root is a good 1st step
This change has been live on our product for more than 6 month
You can find the PR from our fork here -> https://github.com/spotinst/spark-on-k8s-operator/pull/10/files
=> FEATURE: build operator image as non-root

charts/spark-operator-chart/templates/controller/_helpers.tpl
Close #2185 
- Add `list` and `watch` permissions for configmaps
- Add  `get`, `list`, `watch`, `create`, `update`, `patch` and `delete` permissions for persistentvolumeclaims
=> Update controller RBAC for ConfigMap and PersistentVolumeClaim

charts/spark-operator-chart/README.md, charts/spark-operator-chart/templates/controller/deployment.yaml, charts/spark-operator-chart/tests/controller/deployment_test.yaml, charts/spark-operator-chart/values.yaml, cmd/operator/controller/start.go, pkg/util/workqueue.go
Add the capacity to customize the controller workqueue ratelimiter and remove a potential bug on high usage cluster 
- cli argument to modify the default controller-runtime workqueue ratelimiter
- Keep the default value (from controller-runtime) in the code but set them in the chart
With only 10 QPS and 100 Bucket max size we easily reach those number, before migrating to `controller-runtime` the value was actually 50/500 (https://github.com/kubeflow/spark-operator/commit/0dc641bd1d7d262e4a8c5564c926fc4716bcf722#diff-915090b1cf1857dc448319dbbbc11699ba40e674744723a5772a4624a1c79282L59)
We encounter a bug on a high usage cluster a few years ago where we discover that `BucketRatelimiter` rely on …
=> FEATURE: add cli argument to modify controller workqueue ratelimiter

cmd/operator/controller/start.go
Fix ingress API discovery so that driver UI ingresses can be created. This was broken in 2.0.0 because the initialisation function isn't called.
**Old code:**
https://github.com/kubeflow/spark-operator/blob/779ea3debc7885f422a759e6cac6cbcd466c8e5c/main.go#L163-L165
Close https://github.com/kubeflow/spark-operator/issues/2167 
Close https://github.com/kubeflow/spark-operator/issues/2194
=> Fix ingress capability discovery

internal/controller/sparkapplication/submission.go
Close #2221
- return the image option args properly
=> fix: imagePullPolicy was ignored

Dockerfile
fixes #2208 error: `Exception in thread "main" java.io.FileNotFoundException: /home/spark/.ivy2/cache/resolved-org.apache.spark-spark-submit-parent-511288aa-ce7c-4a38-9c8e-4869b71c68fa-1.0.xml (No such file or directory)`
change ownership of `/home/spark` to user `spark`
the issue was introduced by PR #2171
=> fix: spark-submission failed due to lack of permission by user `spark`

Dockerfile
* Remove `setcap 'cap_net_bind_service=+ep'` from the build so the container can be run with all capabilities dropped on a non-privileged port
* Looking at other open source components, it seems more common to run on a non-privileged port and require either root or `NET_BIND_SERVICE` to run on a privileged port e.g. 443
* e.g. https://open-policy-agent.github.io/gatekeeper/website/docs/vendor-specific/#running-on-private-gke-cluster-nodes
* The webhook runs on port 9443 by default which doesn't require any privilege escalation
Run the operator with the following values:
```yaml
controller:
securityContext:
capabilities:
drop: ["ALL"]
webhook:
securityContext:
capabilities:
drop: ["ALL"]
```
https://github.com/kubeflow/spark-operator/issues/2211
Before submitting your PR, please review the …
=> Remove `cap_net_bind_service` from image

internal/webhook/sparkpod_defaulter.go
=> fix: webhook panics due to logging

charts/spark-operator-chart/README.md, charts/spark-operator-chart/templates/controller/deployment.yaml, charts/spark-operator-chart/tests/controller/deployment_test.yaml, charts/spark-operator-chart/values.yaml, cmd/operator/controller/start.go, internal/controller/sparkapplication/controller.go, internal/controller/sparkapplication/controller_test.go, pkg/common/spark.go, pkg/util/sparkpod.go, pkg/util/sparkpod_test.go
In some case executor can enter in a crashlooping state causing the CR to grow out of control
This can have an impact on the entire SparkApplication CR processing reconciliation loop
This can eventually lead to `etcd` errors when we trying to patch / update the CR
- implement a upper bound limit to the number of tracked executor
Submitting apps and tracking driver pods is the highest priority of the spark-operator
1 app going haywire should not hinder the entirety of the cluster
This feature has been live on our fork for the past year -> https://github.com/spotinst/spark-on-k8s-operator/pull/8
=> implement an upper bound limit to the number of tracked executor

Dockerfile, README.md, config/samples/v1beta1_sparkapplication.yaml, config/samples/v1beta2_scheduledsparkapplication.yaml, config/samples/v1beta2_sparkapplication.yaml, examples/spark-pi-configmap.yaml, examples/spark-pi-custom-resource.yaml, examples/spark-pi-dynamic-allocation.yaml, examples/spark-pi-kube-scheduler.yaml, examples/spark-pi-prometheus.yaml, examples/spark-pi-python.yaml, examples/spark-pi-scheduled.yaml, examples/spark-pi-ttl.yaml, examples/spark-pi-volcano.yaml, examples/spark-pi-yunikorn.yaml, examples/spark-pi.yaml, internal/controller/sparkapplication/controller_test.go, spark-docker/Dockerfile
* Upgrade from Spark 3.5.2 to 3.5.3 (https://spark.apache.org/releases/spark-release-3-5-3.html)
* Use new unversioned example JAR path e.g. https://github.com/apache/spark/blob/039fd13eacb1cef835045e3a60cebf958589e1a2/resource-managers/kubernetes/docker/src/main/dockerfiles/spark/Dockerfile#L59
=> Upgrade to Spark 3.5.3

Makefile
Make it a little easier to get started running the e2e tests.
- Correct a typo so now it matches the docs https://www.kubeflow.org/docs/components/spark-operator/developer-guide/#run-e2e-tests.
- Use `$(KIND)` so it uses the `kind` that was automatically installed rather than trying to find it on system path.
=> Minor fixes to e2e test `make` targets

internal/scheduler/yunikorn/resourceusage/memory.go, internal/scheduler/yunikorn/scheduler_test.go
add potential off heap memory into calculations of gang scheduling for yunikorn. As per spark configuration page, 
https://spark.apache.org/docs/latest/configuration.html
- added a new function for adding potential off heap memory like pyspark memory
- fixed a typo in `executorPysparkMemoryBytes`
=> Added off heap memory to calculation for YuniKorn gang scheduling

charts/spark-operator-chart/templates/controller/_helpers.tpl
When in UI ingress creation is enabled, we need the `list` and `watch` permissions for `Ingress` resources.
```
W1014 09:43:21.777501      10 reflector.go:539] pkg/mod/k8s.io/client-go@v0.29.3/tools/cache/reflector.go:229: failed to list *v1.Ingress: ingresses.networking.k8s.io is forbidden: User "system:serviceaccount:spark-operator:spark-operator-controller" cannot list resource "ingresses" in API group "networking.k8s.io" at the cluster scope
E1014 09:43:21.777525      10 reflector.go:147] pkg/mod/k8s.io/client-go@v0.29.3/tools/cache/reflector.go:229: Failed to watch *v1.Ingress: failed to list *v1.Ingress: ingresses.networking.k8s.io is forbidden: User "system:serviceaccount:spark-operator:spark-operator-controller" cannot list resource "ingresses" in API group "networking.k8s.io" at …
```
=> Add permissions to controller serviceaccount to list and watch ingresses

charts/spark-operator-chart/templates/controller/deployment.yaml
Fixes https://github.com/kubeflow/spark-operator/issues/2260
- Set `enable-ui-service` flag to the value of `controller.uiService.enable`, defaults to `true`
=> Make sure enable-ui-service flag is set to false when controller.uiService.enable is set to false

.github/workflows/integration.yaml, Makefile, charts/spark-operator-chart/ci/kind-config.yaml
* Run e2e tests with Kubernetes version matrix containing n-3 of the current Kubernetes versions
=> Run e2e tests with Kubernetes version matrix

charts/spark-operator-chart/README.md, charts/spark-operator-chart/templates/controller/deployment.yaml, charts/spark-operator-chart/tests/controller/deployment_test.yaml, charts/spark-operator-chart/values.yaml
* Allow the `--ingress-class-name` argument to be specified to the controller. This is currently not exposed.
Related: https://github.com/kubeflow/spark-operator/issues/2276
=> Allow --ingress-class-name to be specified in chart

Dockerfile, charts/spark-operator-chart/README.md, charts/spark-operator-chart/values.yaml
- Update default container security context
=> Update default container security context

.github/workflows/release.yaml
Close #1009.
- Add workflow for releasing sparkctl binary
=> Add workflow for releasing sparkctl binary

charts/spark-operator-chart/README.md, charts/spark-operator-chart/templates/controller/deployment.yaml, charts/spark-operator-chart/templates/controller/serviceaccount.yaml, charts/spark-operator-chart/templates/spark/serviceaccount.yaml, charts/spark-operator-chart/templates/webhook/deployment.yaml, charts/spark-operator-chart/templates/webhook/serviceaccount.yaml, charts/spark-operator-chart/values.yaml
By default, kubernetes enables "automountServiceAccountToken" for all pods.
This poses a security risk, as pods might get kube-api permissions unintentionally.
More specifically, this fails security compliance tests:
https://learn.microsoft.com/en-us/azure/governance/policy/samples/built-in-policies
https://www.azadvertizer.net/azpolicyadvertizer/kubernetes_block-automount-token.html
Solution - Disable "automountServiceAccountToken", create projected volume for the token, and mount it on relevant containers
Fixes https://github.com/kubeflow/spark-operator/issues/1189
- Allow setting this field for all spark-operator workloads and serviceAccounts
- No further changes needed, as projected volume can already be added using exiting "volumes" and "volumeMounts" values …
=> Allow setting automountServiceAccountToken

internal/controller/sparkapplication/submission.go
Close #2199 
- When running spark-submit, the emptyDir sizeLimit conf should not be added if sizeLimit is nil.
=> Fix: should not add emptyDir sizeLimit conf if it is nil

charts/spark-operator-chart/README.md, charts/spark-operator-chart/templates/controller/deployment.yaml, charts/spark-operator-chart/templates/webhook/deployment.yaml, charts/spark-operator-chart/tests/controller/deployment_test.yaml, charts/spark-operator-chart/tests/webhook/deployment_test.yaml, charts/spark-operator-chart/values.yaml
Close [#2218 ](https://github.com/kubeflow/spark-operator/issues/2218#issue-2565007558)
- Mount an emptyDir onto the controller container to write Spark artifacts to
- Mount an emptyDir onto the webhook container to write certficates to
- Set the default securityContexts for the controller and webhook to readOnlyRootfilesystem: true
Indicate the type of change by marking the applicable …
=> Allow the Controller and Webhook Containers to run with the securityContext: readOnlyRootfilesystem: true

internal/controller/sparkapplication/submission.go
This is a follow up fix from work already done in https://github.com/kubeflow/spark-operator/pull/2305 by @ChenYi015 
This PR adds a check at submission on executors pods if an emptyDir `sizeLimit` is `nil`.  
Following some further testing of an older `SparkApplication` template wherein the volumeName (see issue https://github.com/kubeflow/spark-operator/issues/2199 for more details) had not been changed, I noticed behaviour wherein only the driver pod would get created and no executor pods would spawn. I believe this is due to the same issue outlined in https://github.com/kubeflow/spark-operator/pull/2305 which would make sense, as the check was only added on the driver pod submission, and not the executors.
=> Fix: should not add emptyDir sizeLimit conf on executor pods if it is nil

go.mod, go.sum
Close https://github.com/kubeflow/spark-operator/issues/2318
* Upgrade `volcano.sh/apis` to `1.10.0` to ensure a critical vulnerability doesn't appear on any automated scans https://github.com/advisories/GHSA-5g3x-8g2v-r8x8.
* The vulnerability is related to RBAC permissions on the Volcano deployment and not our usage of the APIs package.
=> Bump `volcano.sh/apis` to 1.10.0

pkg/util/sparkapplication.go, pkg/util/sparkapplication_test.go
Truncate the UI service name while appending a hash to ensure uniqueness if longer than 63 characters.
Close https://github.com/kubeflow/spark-operator/issues/2300
=> Truncate UI service name if over 63 characters

cmd/operator/webhook/start.go
The command-line parameter "webhookKeyName" is appropriately passed-in webhook options object to override the default name "tls.key".
=> The webhook-key-name command-line param isn't taking effect

charts/spark-operator-chart/README.md, charts/spark-operator-chart/templates/controller/deployment.yaml, charts/spark-operator-chart/tests/controller/deployment_test.yaml, charts/spark-operator-chart/values.yaml, cmd/operator/controller/start.go, internal/controller/sparkapplication/controller.go, internal/controller/sparkapplication/controller_test.go
Improve reliability. 
Closes: #2302
- Add a grace period for the driver pod to be created. 
- Grace period is controlled by a new config option `driver-pod-creation-grace-period`. Default is 10 seconds. 
- Add 3 new tests around reconciling submitted status, including the new grace period functionality. This is the majority of the lines changed. 
- Expose the new config option in the helm chart and add a helm test
Some logs of a real example on our prod cluster where the spark application was saved by the grace period added in this PR. 
[Explore-logs-2024-11-11 12_09_13.txt](https://github.com/user-attachments/files/17702165/Explore-logs-2024-11-11.12_09_13.txt)
=> Robustness to driver pod taking time to create

charts/spark-operator-chart/README.md, charts/spark-operator-chart/values.yaml
- Adding `seccompProfile type: RuntimeDefault` to controller and webhook 
https://github.com/kubeflow/manifests/issues/2912#issuecomment-2603066080
=> Adding seccompProfile RuntimeDefault

examples/spark-pi-prometheus-servlet.yaml
- Adds an example of using prometheus servlet natively available in spark.
You can do something like this to verify. 
```bash
$ kubectl port-forward pod/spark-pi-python-driver 3000:4040
```
```bash
$ curl localhost:3000/metrics/executors/prometheus
spark_info{version="3.5.3", revision="32232e9ed33bb16b93ad58cfde8b82e0f07c0970"} 1.0
metrics_executor_rddBlocks{application_id="spark-c8519a1215934adba443bc7cd1108a1c", application_name="PythonPi", executor_id="driver"} 0
metrics_executor_memoryUsed_bytes{application_id="spark-c8519a1215934adba443bc7cd1108a1c", application_name="PythonPi", executor_id="driver"} 8959
metrics_executor_diskUsed_bytes{application_id="spark-c8519a1215934adba443bc7cd1108a1c", application_name="PythonPi", executor_id="driver"} 0 …
```
=> add an example of using prometheus servlet

cmd/sparkctl/app/event.go, go.mod, go.sum, pkg/util/interrupt.go
* Remove dependency on `k8s.io/kubernetes` by bringing the interrupt handler structure into the repo. 
* `k8s.io/kubernretes` is not intended to be used by any external projects, causes headaches when trying to upgrade `k8s.io` dependencies and requires `replace` directives in the `go.mod`.
https://github.com/kubernetes/kubernetes/issues/79384
=> Remove dependency on `k8s.io/kubernetes`

Makefile
Currently `make deploy` and `make install-crd` are broken. This PR aims to fix it.
fixes: #2386 
- For `make deploy`, I followed the e2e-test logic where it deploys using the helm chart directory and the value file for CI.
- For `make install-crd`, I am using `kubectl replace` instead of apply to avoid overloading annotations.
- I've also updated the default kind node image to `v1.29.12` because `v1.29.3` [does not exist anymore](https://hub.docker.com/r/kindest/node/tags?name=1.29.3).
Example outputs.
```
$ make deploy
NAME: spark-operator
LAST DEPLOYED: Tue Jan 28 21:02:43 2025
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
$ k get pods
NAME                                         READY   STATUS    RESTARTS   AGE …
```
=> fix make deploy and install

charts/spark-operator-chart/README.md, charts/spark-operator-chart/templates/controller/deployment.yaml, charts/spark-operator-chart/templates/controller/rbac.yaml, charts/spark-operator-chart/templates/webhook/deployment.yaml, charts/spark-operator-chart/templates/webhook/rbac.yaml, charts/spark-operator-chart/tests/controller/deployment_test.yaml, charts/spark-operator-chart/tests/webhook/deployment_test.yaml, charts/spark-operator-chart/values.yaml
Close #2384
- Add option `controller.leaderElection.enable` and `webhook.leaderElection.enable` for disabling controller/webhook leader election
- When leader election was disabled, the related RBAC rules against leases will be removed.
=> Add option for disabling leader election

internal/controller/sparkapplication/controller.go
Currently, the controller uses [context.Todo](https://pkg.go.dev/context#TODO) in its main logic, it's usually a better practice to use passed in context if available, instead of using the background context. This will allow it to set context on start up and use the same context in the future. 
- Replace `context.Todo()` with passed in context.
=> ensure passed context is used

charts/spark-operator-chart/templates/controller/_helpers.tpl, charts/spark-operator-chart/templates/controller/rbac.yaml
Close #2402 
Proposed changes:
- Remove the event permissions from ClusterRole
- Grant the event permissions to controller in every Spark job namespace
=> Controller should only be granted event permissions in spark job namespaces

cmd/sparkctl/app/create.go, cmd/sparkctl/app/log.go, cmd/sparkctl/app/root.go
Currently, sparkctl uses [context.Todo](https://pkg.go.dev/context#TODO) whenever it talks to k8s api. It's usually a better idea to create a context for cobra, then use it for subcommand executions. This will allow for a bit more complex things in the future like command timeout.
- Create a root context in the root command.
- In subcommands, retrieve the context through Cobra's `cmd.Context()`. Then use it for the rest of execution processes.
=> use cmd context in sparkctl

internal/controller/sparkapplication/submission.go
- Make `app.Spec.Driver.Image` `app.Spec.Executor.Image` and `app.Spec.Image` optional as defined in the api-docs. This is the behavior in Spark Operator V1. A use-case here is setting the image via `spark.kubernetes.container.image` Spark configuration in spark-defaults.conf or `spec.sparkConf`.
=> Make image optional

internal/webhook/sparkpod_defaulter.go
- If using a non-standard container name for Spark driver or executor container, assume that the first container in the list is the Spark container, which is what [Spark assumes](https://spark.apache.org/docs/latest/running-on-kubernetes.html#pod-template). See **Rationale** section for further explanation.
Current implementation only supports standard Spark container names. Driver container name must be `spark-kubernetes-driver` and executor container name must be `spark-kubernetes-executor` or `executor`. However, Pod template files can define multiple containers, and you can use the spark properties spark.kubernetes.driver.podTemplateContainerName and spark.kubernetes.executor.podTemplateContainerName to indicate which container should be used as a basis for the …
=> Support non-standard Spark container names

.github/workflows/integration.yaml
Integration tests for helm chart are failing after chart-testitng-action was bumped to 2.7.0: https://github.com/kubeflow/spark-operator/pull/2391
This introduced a breaking change from chart-testing: 
- https://github.com/helm/chart-testing-action/releases/tag/v2.7.0
- https://github.com/helm/chart-testing/releases/tag/v3.11.0
Tests fail with `targetBranch 'origin/main' does not exist`.
See: https://github.com/kubeflow/spark-operator/actions/runs/13597275163/job/38016877250
Tested the change introduced here in my own repository. They do work: 
- https://github.com/nabuskey/spark-operator/commit/942d590d86962f2df29a0e859a9fb891ff8fa105
- https://github.com/nabuskey/spark-operator/pull/1
- Specify the branch name explicitly in the `ct install` command.
See above.
=> specify branch name in chart testing

charts/spark-operator-chart/README.md, charts/spark-operator-chart/templates/controller/deployment.yaml, charts/spark-operator-chart/tests/controller/deployment_test.yaml, charts/spark-operator-chart/values.yaml
This adds support for the [metrics-job-start-latency-buckets](https://github.com/kubeflow/spark-operator/blob/79264a4ac559cd6373b43bb54365d566b2537acb/cmd/operator/controller/start.go#L176) flag in Helm. Currently there's no support for it and the default max value of 300 is too low for some testing scenarios. This PR makes it configurable in Helm.
The default value is taken from the command line flag default value.
- Add support for the `metrics-job-start-latency-buckets` flag in helm.
During our stress testing of this operator, we found the default max value of 300 inadequate because our testing setup pushed the operator to take more than 5 minutes to process all items in its queue.
=> add support for metrics-job-start-latency-buckets flag in helm

Makefile, cmd/sparkctl/README.md, cmd/sparkctl/main.go
This  PR is to mark sparkCtl deprecated in preparation for #2465 
- mark sparkctl deprecated
- advice users to move to another alternative e.g. kubectl
=> Deprecating sparkctl

pkg/certificate/certificate.go, pkg/certificate/certificate_test.go
Invalid certificates stored in the webhook secret are used without validation.  This can lead to certificate expired or name validation errors during a webhook call.
Fixes https://github.com/kubeflow/spark-operator/issues/2482
- use the x509.Certificate.Verify method to check if the certificate is valid and regenerate it if not.
=> fix: add webhook cert validity checking

.github/workflows/integration.yaml, .github/workflows/release.yaml, Makefile, charts/spark-operator-chart/README.md, charts/spark-operator-chart/values.yaml
As per the kubeflow wide initiative to migrate all images from docker.io to ghcr.io kubeflow/maniifests#3010 , I am am making the change to do the same. the sparkoperator repo specific issue is #2480 
- change  image registry to ghcr.io
This change is a part of Kubeflow wide initiative  kubeflow/maniifests#3010
Additional comments 
/closes #2480
=> Changing image repo from docker.io to  ghcr.io

api/v1beta2/scheduledsparkapplication_types.go, charts/spark-operator-chart/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml, config/crd/bases/sparkoperator.k8s.io_scheduledsparkapplications.yaml, docs/api-docs.md, internal/controller/scheduledsparkapplication/controller.go
* Allow a timezone to be specified in a `ScheduledSparkApplication`
* Explicitly validate the timezone for better user feedback
* Ensure backwards compatibility if any users are relying on `CRON_TZ=` or `TZ=` prefixes in the schedule field being parsed by `robfig/cron`
Close https://github.com/kubeflow/spark-operator/issues/1712 
Close https://github.com/kubeflow/spark-operator/issues/2328
=> Add timeZone to ScheduledSparkApplication

api/v1beta2/sparkapplication_types.go, api/v1beta2/zz_generated.deepcopy.go, charts/spark-operator-chart/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml, charts/spark-operator-chart/crds/sparkoperator.k8s.io_sparkapplications.yaml, config/crd/bases/sparkoperator.k8s.io_scheduledsparkapplications.yaml, config/crd/bases/sparkoperator.k8s.io_sparkapplications.yaml, docs/api-docs.md, internal/webhook/sparkpod_defaulter.go, internal/webhook/sparkpod_defaulter_test.go, pkg/util/util.go, pkg/util/util_test.go
Add the ability to setup `memoryLimits` definition through webhook. 
The changes were originally part of the development of https://github.com/kubeflow/spark-operator/pull/2383 and https://github.com/kubeflow/spark-operator/pull/2389.
This changes addresses the community most reacted issue https://github.com/kubeflow/spark-operator/issues/1489.
A few users have created their own custom version of either SparkOperator or Kubernetes Admission Controller to enable memoryLimits with a different value than memory requested.
It was first raised here https://github.com/kubeflow/spark-operator/pull/1990. The pull request 1990 contained two features: memoryLimits and queue boost. Since the second part was covered in another PR, the 1990 was closed and the memoryLimits was not …
=> Enable the override of MemoryLimit through webhook

api/v1beta2/sparkapplication_types.go, api/v1beta2/zz_generated.deepcopy.go, charts/spark-operator-chart/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml, charts/spark-operator-chart/crds/sparkoperator.k8s.io_sparkapplications.yaml, config/crd/bases/sparkoperator.k8s.io_scheduledsparkapplications.yaml, config/crd/bases/sparkoperator.k8s.io_sparkapplications.yaml, docs/api-docs.md, internal/controller/sparkapplication/submission.go, internal/webhook/sparkapplication_defaulter.go, pkg/util/sparkapplication.go, pkg/util/sparkapplication_test.go
Add ShuffleTrackingEnabled *bool to DynamicAllocation so that shuffle tracking can be disabled when using an external shuffle service. Set default for ShuffleTrackingEnabled to true if dynamicAllocation.enabled is true so that it's not a breaking change.
- Add ShuffleTrackingEnabled *bool to DynamicAllocation struct
- Set default for ShuffleTrackingEnabled to true if dynamicAllocation.enabled is true
- Set `spark.dynamicAllocation.shuffleTracking.enabled` spark conf based on ShuffleTrackingEnabled value
Currently if dynamicAllocation is enabled, shuffle tracking is enabled by default. When using an external shuffle service,
we want dynamicAllocation to be enabled and want shuffle tracking to be disabled. So adding a variable to allow users to 
disable shuffle …
=> Add ShuffleTrackingEnabled to DynamicAllocation struct to allow disabling shuffle tracking

internal/controller/sparkapplication/monitoring_config.go, internal/controller/sparkapplication/monitoring_config_test.go, pkg/util/sparkapplication.go
- <Change 1>
- <Change 2>
- <Change 3>
#2525
=> #2525 spark metrics in depends on prometheus

charts/spark-operator-chart/README.md, charts/spark-operator-chart/ci/ci-values.yaml, charts/spark-operator-chart/templates/controller/deployment.yaml, charts/spark-operator-chart/tests/controller/deployment_test.yaml, charts/spark-operator-chart/values.yaml, cmd/operator/controller/start.go, internal/controller/sparkapplication/controller.go, internal/controller/sparkapplication/controller_test.go, internal/controller/sparkapplication/driveringress.go, internal/controller/sparkapplication/web_ui.go
Support helm chart level defaults for ingress TLS and annotations, so they don't need to be configured on every SparkApplication. 
Closes: https://github.com/kubeflow/spark-operator/issues/2460
- Add CLI arguments `--ingress-tls` and `--ingress-annotations` and use them when TLS/annotations are not provided in the SparkApplication's spec. These are provided as JSON strings in the CLI. 
- Expose these via the helm config. The user configures them as normal in the helm yaml and they get serialised to JSON, so they can be read by the controller. 
- Wrote unit tests. 
I considered adding an e2e test to cover the helm and CLI configuration. However, I couldn't see a way to run the e2e tests with multiple helm configs. I could have changed all the e2e tests to use these …
=> Make default ingress tls and annotations congurable in the helm config

internal/controller/sparkapplication/controller.go
PR loosely related to https://github.com/kubeflow/spark-operator/issues/1263
Splats args provided to `recordExecutorEvent` to avoid missing interpolation in event messages.
Without this change you'll get messages that look like this:
```
Executor [spark-pi-python-oomer-9ee50397e27f13ad-exec-3 %!s(int32=137) OOMKilled] failed with ExitCode: %!d(MISSING), Reason: %!s(MISSING)
```
With this change they look like this instead:
```
Executor spark-pi-python-oomer-8cfd2197e269b2ec-exec-1 failed with ExitCode: 137, Reason: OOMKilled
```
- ~I have updated documentation accordingly.~ no documentation found on event formatting
- ~I have added tests that prove my changes are effective or that my feature works.~ see Additional Notes
It looks like the `args` slice was introduced back in …
=> Splat recordExecutorEvent args for cleaner event messages

internal/controller/sparkapplication/controller.go
PR loosely related to https://github.com/kubeflow/spark-operator/issues/1263
This adds `pod.Status.Message` to the event message produced by `recordExecutorEvent`
- Append `pod.Status.Message` content to the message produced by recordExecutorEvent, if available in the pod data
This is especially useful for ephemeral-storage exhaustion. In this case you don't get a container termination reason since the storage is pod-level. The yaml ends up looking like this:
```yaml
containerStatuses:
- name: spark-kubernetes-executor 
ready: false
restartCount: 0
started: false
state:
terminated:
containerID: containerd://0f83df84ff6f209c16fc98833eb904f4976bdd054f18ec81e328bf96622ae282
exitCode: 143
finishedAt: "2025-07-09T20:10:38Z"
reason: Error
startedAt: "2025-07-09T20:07:47Z" …
```
=> Include pod.Status.Message in recordExecutorEvent

api/v1alpha1/sparkconnect_types.go, charts/spark-operator-chart/crds/sparkoperator.k8s.io_sparkconnects.yaml, config/crd/bases/sparkoperator.k8s.io_sparkconnects.yaml
This adds two additional print columns: `state` and `podname`. Adding them should make it easier for end users to figure out what is happening to the spark connect server.
```
k get sparkconn
NAME            AGE   STATUS     PODNAME
spark-connect   59s   NotReady   spark-connect-server
```
- adds two additional print columns: `state` and `podname`
- <Change 2>
- <Change 3>
=> Add print columns for Spark Connect

charts/spark-operator-chart/templates/controller/rbac.yaml
* Grant create events permissions to Controller in it's own namespace
- Grant the controller permission to create, update, patch events in it's own namespace
=> Grant create events permissions to Controller

charts/spark-operator-chart/README.md, charts/spark-operator-chart/templates/controller/deployment.yaml, charts/spark-operator-chart/templates/webhook/deployment.yaml, charts/spark-operator-chart/tests/controller/deployment_test.yaml, charts/spark-operator-chart/tests/webhook/deployment_test.yaml, charts/spark-operator-chart/values.yaml
The PR adds configuration option for revisionHistoryLimit to control the number of old ReplicaSets for rollback.
There will be no changes in default behaviour.
- https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#revision-history-limit
=> fix(chart): add revisionHistoryLimit option

internal/controller/sparkconnect/options.go
Previously, the `spec.executor.memory` value in `SparkConnect` was not passed to `--conf spark.executor.memory`. This caused executors to ignore the configured memory setting. The fix ensures that the memory value is correctly applied to the Spark configuration.
=> fix(connect): propagate executor memory setting to spark options
