kubeflow/spark-operator

pkg/controller/spark_pod_monitor.go, pkg/initializer/initializer.go
This is because we may move to using an admission webhook to replace the initializer in the future and also because the two are using different ListWatch anyway.
=> Do not use shared informer in the initializer and pod monitor

manifest/spark-operator.yaml, pkg/apis/sparkoperator.k8s.io/v1alpha1/types.go, pkg/controller/controller.go, pkg/controller/spark_pod_monitor.go, pkg/controller/submission_runner.go
Unless submission fails, in which case the application state is set to "SUBMISSION_FAILED".
@ozzieba
=> Set application state based on driver pod phase

pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/controller/spark_pod_monitor.go, pkg/controller/spark_pod_monitor_test.go
Combined communicating driver and executor pod updates into a single channel.
=> Simplified the handling of pod state updates

pkg/controller/controller.go
Also refactored the code around enqueueing/dequeueing for event recording.
=> Added a placeholder for handling updates

pkg/controller/controller.go, pkg/controller/controller_test.go
=> Enable cache re-sync

README.md, docs/api.md, docs/quick-start-guide.md, docs/user-guide.md, pkg/apis/sparkoperator.k8s.io/v1alpha1/types.go
=> Added draft version of the user guide

sparkctl/README.md, sparkctl/cmd/log.go
=> Added support for streaming logs to sparkctl

README.md
=> Add the slack channel

docs/api.md, docs/user-guide.md, pkg/apis/sparkoperator.k8s.io/v1alpha1/types.go, pkg/apis/sparkoperator.k8s.io/v1alpha1/zz_generated.deepcopy.go, pkg/controller/scheduledsparkapplication/controller.go, pkg/controller/scheduledsparkapplication/controller_test.go
=> Added SuccessfulRunHistoryLimit and FailedRunHistoryLimit

pkg/controller/sparkapplication/controller.go, pkg/controller/sparkapplication/controller_test.go
=> Fixed a bug that may lead to duplicated restarts when RestartPolicy!=Never

pkg/controller/sparkapplication/controller.go
=> Skip restart if the pod or UI service of the old run was not found

manifest/spark-operator-rbac.yaml
=> Fixed RBAC for the operator to grant just the necessary permissions

pkg/config/configmap.go, pkg/config/configmap_test.go
Fixes: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/165
Unit tests and manual functional
@liyinan926 @prasanthkothuri @LucaCanali
=> Fix bug with doubled SPARK_CLASSPATH env

sparkctl/README.md
For Go beginners, it might be valuable to state that there're instructions on how to build the operator and get dependencies prior to building sparkctl.
=> Ensure all dependencies are present comment

docs/quick-start-guide.md, main.go, pkg/controller/sparkapplication/controller.go, pkg/controller/sparkapplication/controller_test.go, pkg/controller/sparkapplication/spark_pod_monitor.go, pkg/controller/sparkapplication/spark_pod_monitor_test.go, pkg/initializer/initializer.go, pkg/initializer/initializer_test.go
=> add -namespace flag to manage only CRDs in that namespace

Dockerfile
This will allow the operator to be used with spark images that differs from the operator image (alpine).
=> Platform agnostics operator binary with static compiling

pkg/controller/sparkapplication/sparkui.go, pkg/controller/sparkapplication/sparkui_test.go
=> Shorten the name of the driver UI service

pkg/apis/sparkoperator.k8s.io/v1alpha1/register.go, pkg/apis/sparkoperator.k8s.io/v1beta1/register.go, pkg/apis/sparkoperator.k8s.io/v1beta1/types.go, pkg/crd/scheduledsparkapplication/crd.go, pkg/crd/sparkapplication/crd.go
This is the first step in the direction of addressing #182.
=> Added SparkVersion to the v1beta1 API

sparkctl/README.md
Adjustment of documentation for https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/253 @liyinan926
=> Adjust sparkctl documentation for event cmd

examples/spark-pi-prometheus.yaml, pkg/apis/sparkoperator.k8s.io/v1alpha1/types.go, pkg/apis/sparkoperator.k8s.io/v1beta1/types.go, pkg/config/constants.go, pkg/controller/sparkapplication/controller.go, pkg/controller/sparkapplication/monitoring_config.go, pkg/controller/sparkapplication/monitoring_config_test.go, pkg/controller/sparkapplication/submission.go
=> Add support for automatic configuration for exposing driver/executor metrics to Prometheus

README.md, docs/api.md, docs/user-guide.md
=> Added documentation for #255

docs/quick-start-guide.md
Also fixed some minor formatting issues.
=> Updated doc to use Helm chart

sparkctl/cmd/list.go, sparkctl/cmd/status.go
Result is: 
```
+----------+-------+---------------+---------------+
|   NAME   | STATE | SUBMITTED AGE | COMPLETED AGE |
+----------+-------+---------------+---------------+
| spark-pi | NEW   | N.A.          | N.A.          |
+----------+-------+---------------+---------------+
```
or 
```
+----------+-----------+---------------+---------------+
|   NAME   |   STATE   | SUBMITTED AGE | COMPLETED AGE |
+----------+-----------+---------------+---------------+
| spark-pi | COMPLETED | 4m            | 2m            |
+----------+-----------+---------------+---------------+
```
=> Unify listing application with status/event for sparkctl

README.md, docs/api.md, docs/design.md, docs/quick-start-guide.md, docs/user-guide.md, docs/who-is-using.md
As required for https://github.com/apache/spark-website/pull/148.
=> Used "Kubernetes Operator for Apache Spark" in documentation

README.md, docs/quick-start-guide.md
=> Fixed documentation after the go import path change

docs/quick-start-guide.md, hack/gencerts.sh, manifest/spark-operator-rbac.yaml, manifest/spark-operator-with-metrics.yaml, manifest/spark-operator-with-webhook.yaml, manifest/spark-operator.yaml
Fix the namespace for sparkoperator deployment
=> Fix the namespace for sparkoperator deployment

.travis.yml, Gopkg.lock, pkg/controller/sparkapplication/submission_runner.go
=> Upgraded to go 1.11

docs/quick-start-guide.md, docs/user-guide.md, manifest/spark-operator-crds.yaml
=> Added yamls for CRDs for case where install-crds=false

examples/spark-py-pi.yaml, manifest/spark-operator-with-metrics.yaml, manifest/spark-operator-with-webhook.yaml, manifest/spark-operator.yaml, pkg/controller/sparkapplication/controller.go, pkg/controller/sparkapplication/controller_test.go, pkg/controller/sparkapplication/submission.go
1. Fixed SparkApplication controller to ignore reconcilation caused by SparkApplication not found errors.
2. Fixed the PySpark example.
3. Fixed code for updating the status of a SparkApplication in updateAndExportMetrics.
4. Logging refactoring.
=> Various fixes for the operator

docs/who-is-using.md
MapR is currently evaluating spark-operator for their data platform for running Spark application and using spark-operator for managing and maintaining spark applications.
=> Update who-is-using for MapR Technologies

pkg/controller/sparkapplication/controller.go, pkg/controller/sparkapplication/monitoring_config.go, pkg/controller/sparkapplication/monitoring_config_test.go
the code path would fail silently with a misconfiguration
- string format work around for prometheus push gateway issue:
https://github.com/prometheus/pushgateway/issues/97
=> - added error logging for prometheus configuration issues, otherwise

manifest/spark-operator-crds.yaml
Partially fixes #364
@liyinan926 @sarjeet2013
=> Provide field validation in SparkApplication CRD yaml

pkg/controller/sparkapplication/submission.go
=> Surface the actual submission error message

pkg/controller/sparkapplication/submission.go
=> Set Controller in OwnerReference on driver pods

pkg/controller/sparkapplication/controller.go, pkg/controller/sparkapplication/spark_pod_eventhandler.go, pkg/controller/sparkapplication/submission.go, pkg/webhook/webhook.go
Recently we saw an issue with mutation in our cluster. For some reason pod was not being mutated
and the exact condition was not known. So we need more logging.
Adds some more logging to other areas.
=> Add more logging to the webhook and other areas

docs/user-guide.md, pkg/apis/sparkoperator.k8s.io/v1beta1/types.go, pkg/webhook/patch.go, pkg/webhook/patch_test.go, pkg/webhook/webhook_test.go
=> Added support for specifying PodSecurityContext

Gopkg.lock, Gopkg.toml
Reverts GoogleCloudPlatform/spark-on-k8s-operator#439
=> Revert "Pinned k8s.io/code-generator to the same version as other k8s.io deps"

pkg/controller/sparkapplication/controller.go, pkg/controller/sparkapplication/controller_test.go, pkg/controller/sparkapplication/sparkapp_metrics.go, pkg/controller/sparkapplication/sparkapp_metrics_test.go
=> Fixed a bug related to app update and restart

Gopkg.lock, Gopkg.toml
=> Fixed Docker build

pkg/apis/sparkoperator.k8s.io/v1beta1/types.go, pkg/config/config.go, pkg/config/constants.go, pkg/controller/sparkapplication/controller.go, pkg/controller/sparkapplication/monitoring_config.go, pkg/controller/sparkapplication/monitoring_config_test.go, pkg/webhook/patch.go, pkg/webhook/patch_test.go
=> Fixed mounting of Prometheus configuration ConfigMap

docs/quick-start-guide.md
=> Fix a typo

pkg/controller/sparkapplication/controller.go
In some cases, the driver may be accessible if within internal network - thus `app.Status.DriverInfo.WebUIAddress` should show external IP address if such is available, but also internal IP if this is the only one available.
@liyinan926
=> For DriverInfo.WebUIAddress, return internal ip of node if external ip not found

pkg/controller/sparkapplication/controller.go, pkg/controller/sparkapplication/controller_test.go
@liyinan926  PTAL . I think this will be useful to expose reason why the driver pod failed like OOM etc. which we see quite a bit. Let me know if you have any questions/concerns.
=> Expose Driver Container Error Code on Pod Failure

pkg/controller/sparkapplication/job.go
We use  annotations for various purposes including to associate IAM roles to Pods. Ran into a situation where we need s3 access from the  spark-submit pod if the user wants to use `spark.jars` stored on s3. 
This passes in job/CRD annotations to the pod as well.
=> Pass on labels/annotations to spark-submit pod

.travis.yml, Dockerfile, Dockerfile.rh, pkg/controller/sparkapplication/sparkui_test.go, test/e2e/framework/helpers.go
And minor fixes for deprecated usage.
=> Updated Go and dep versions

docs/developer-guide.md
Hi, this PR adds a section to `developer-guide.md` about HA support. 
:)
=> Add develop guide about HA support

docs/user-guide.md, pkg/apis/sparkoperator.k8s.io/v1beta1/types.go, pkg/webhook/patch.go, pkg/webhook/patch_test.go
Hi
This patch adds the option to override the command and args for the driver and executor.
=> Added support for overriding command and args

pkg/apis/sparkoperator.k8s.io/v1beta1/zz_generated.deepcopy.go, pkg/client/clientset/versioned/clientset.go, pkg/client/clientset/versioned/fake/clientset_generated.go
=> Fixed auto-generated code

pkg/apis/sparkoperator.k8s.io/v1alpha1/doc.go, pkg/apis/sparkoperator.k8s.io/v1beta1/doc.go, pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1alpha1/fake/fake_scheduledsparkapplication.go, pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1alpha1/fake/fake_sparkapplication.go, pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1alpha1/sparkoperator.k8s.io_client.go, pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1beta1/fake/fake_scheduledsparkapplication.go, pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1beta1/fake/fake_sparkapplication.go, pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1beta1/sparkoperator.k8s.io_client.go, pkg/client/informers/externalversions/generic.go
=> Fixed the group name annotation in doc.go

docs/quick-start-guide.md
Added documentation for Work Queue metrics as seen in `pkg/util/metrics.go`
=> Added metrics documentation to reflect code

docs/api.md
Tiny PR to fix api structure docs.
=> [DOCS] Update api doc structure

main.go
For some reason, adding the callbacks after starting the informer causes a deadlock in `WaitForCacheSync`:
```
goroutine 1 [chan receive]:
github.com/GoogleCloudPlatform/spark-on-k8s-operator/vendor/k8s.io/apimachinery/pkg/util/wait.WaitFor(0xc0003910a0, 0xc00058fb30, 0xc0000c20c0, 0x231e998, 0xc00058fb50)
/home/khogeland/go/src/github.com/GoogleCloudPlatform/spark-on-k8s-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:330 +0x58
github.com/GoogleCloudPlatform/spark-on-k8s-operator/vendor/k8s.io/apimachinery/pkg/util/wait.PollUntil(0x5f5e100, 0xc00058fb30, 0xc0000c20c0, 0x43781f, 0xc00058fb20)
/home/khogeland/go/src/github.com/GoogleCloudPlatform/spark-on-k8s-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:290 +0x56 …
```
=> Deadlock fix: add informer callbacks before starting informers

Makefile
improved Makefile
1. new target for installing (OS sensitive) - will fail if no previous build
2. default all target with complete build and install 
3. typo fix in .PHONY targets
4. build once
=> added install target for linux and macos + typo fix

pkg/controller/sparkapplication/controller.go
=> Check application expiration in OnUpdate

.gitignore
=> Fix .gitignore typo

README.md
=>  Updated the Prerequisite section of README.md

sparkctl/cmd/delete.go, sparkctl/cmd/list.go, sparkctl/cmd/log.go
=> Fixed the client version used in sparkctl

pkg/webhook/resourceusage/watcher.go
Fixes https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/690
=> Fix CRD informer version in resource usage watcher

sparkctl/README.md
fix copy&paste error & grammar
=> fixing copy&paste error in sparkctl Readme

pkg/controller/sparkapplication/job.go
Temporary solution until #730 is resolved
=> Higher memory limit for spark-submit pod

pkg/batchscheduler/interface/interface.go, pkg/batchscheduler/volcano/volcano_scheduler.go, pkg/controller/sparkapplication/controller.go
Reverts GoogleCloudPlatform/spark-on-k8s-operator#804
=> Revert "Fixed the spec update issue in #795"

docs/user-guide.md
This would make it match the location.
=> Make spark-local-dir-1 be spark-local-dir-2

docs/design.md
Updated a broken link and reference on the page.
=> Update links design.md

pkg/controller/sparkapplication/controller.go, pkg/controller/sparkapplication/sparkapp_metrics.go, pkg/controller/sparkapplication/sparkapp_util.go, pkg/controller/sparkapplication/sparkapp_util_test.go
Refactored the code a bit so no status update log message gets produced if the status has not changed. Also used json pretty printing for status strings, which will be much more readable than simply printing the go object.
=> Refactored how status update is logged

README.md
=> Link on README led to 404

manifest/spark-operator-rbac.yaml, pkg/batchscheduler/volcano/volcano_scheduler.go, pkg/controller/sparkapplication/controller.go
Signed-off-by: Peng Gao <peng.gao.dut@gmail.com>
=> Set podgroup to stable version

pkg/webhook/patch.go
=> Fixed issue #927

pkg/controller/sparkapplication/submission_test.go
related to issue [#942](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/942).
=> (issue #942) Fix unit tests in submission_test

examples/spark-pi-custom-resource.yaml, pkg/apis/sparkoperator.k8s.io/v1beta2/types.go, pkg/batchscheduler/volcano/volcano_scheduler.go, pkg/batchscheduler/volcano/volcano_scheduler_test.go, test/e2e/basic_test.go
- support custom resource request for volcano
- add basic e2e case for the feature
Signed-off-by: Thor <1187526662@qq.com>
=> volcano scheduler support custom request resource

docs/who-is-using.md
Hi, [PUBG](https://careers.pubg.com/#/en/) has been using spark-on-k8s-operator.
=> Add PUBG to who is using

docs/who-is-using.md
In this PR:
1. Added Stitch Fix to the who-is-using doc.
2. Fixed some spacing nits for the doc itself to be consistent.
=> Add Stitch Fix under who-is-using

docs/who-is-using.md
Add MongoDB to the list of who-is-using.md
=> Add MongoDB to who-is-using.md

docs/who-is-using.md
We, at Gojek, are using spark operator for performing distributed batch prediction in [Merlin](https://github.com/gojek/merlin). It has been working quite well and having strong adoption internally.
=> Include Gojek in who-is-using.md

charts/spark-operator-chart/values.yaml
correct name forhook is `pre-upgrade` and not `pre-update` https://helm.sh/docs/topics/charts_hooks/
=> correct hook annotation for webhook job

sparkctl/README.md, sparkctl/cmd/create.go, sparkctl/cmd/s3.go
added --s3-force-path-style to choose whether to force path style URLs for S3 objects
=> added --s3-force-path-style to force path style URLs for S3 objects

pkg/controller/sparkapplication/job.go
=> Support nodeSelector in spark-submit pod

docs/volcano-integration.md
fix: #1289 
Signed-off-by: william-wang <wang.platform@gmail.com>
=> fix the invalid repo address

charts/spark-operator-chart/Chart.yaml, charts/spark-operator-chart/templates/spark-rbac.yaml
=> [FIX] add service account access to persistentvolumeclaims

pkg/controller/sparkapplication/controller.go
Fixes https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1517.
=> Fix Spark UI URL in app status

charts/spark-operator-chart/Chart.yaml, pkg/controller/sparkapplication/controller.go
Fixes https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1467. Refactored from https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/1485 as a single PR.
=> Fixes issue #1467 (issue when deleting SparkApplication without metrics server)

docs/user-guide.md
Like Init-Containers, Sidecars require mutating admission webhooks to work.
=> Update README - secrets and sidecars need mutating webhooks

docs/who-is-using.md
Used to run Analytics Jobs and ETL pipelines along with AI/ML jobs.
=> Molex started using spark K8 operator.

docs/who-is-using.md
We also want to contribute to maintaining this repo
=> Added qualytics to who is using

docs/quick-start-guide.md
Installing operator using kustomize and custom namespace and service name
=> README for installing operator using kustomize with custom namespace and service name

.pre-commit-config.yaml, charts/spark-operator-chart/README.md, charts/spark-operator-chart/README.md.gotmpl
- Replace previous helm repo with the new one in helm docs and update usage
- Add `.pre-commit-config.yaml` file to generate helm docs before commit
=> Update helm chart README

.github/workflows/main.yaml, .github/workflows/release.yaml, charts/spark-operator-chart/Chart.yaml, charts/spark-operator-chart/README.md, charts/spark-operator-chart/values.yaml
As we discussed, I used Kubeflow Docker Hub for Spark Operator images.
/assign @vara-bonthu @yuchaoran2011
=> Use Kubeflow Docker Hub for Spark Operator Image

charts/spark-operator-chart/Chart.yaml, charts/spark-operator-chart/README.md, charts/spark-operator-chart/templates/rbac.yaml
Close #1960 
- spark operator rbac: remove the `create`, `update` and `delete` permissions for CustomResourceDefinition
The reason is described in #1960 .
=> Update spark operator permissions for CRD

.github/workflows/release.yaml
This should fix the `Login to Packages Container registry` GitHub action.
/assign @vara-bonthu @yuchaoran2011
=> Fix Docker Hub Credentials in CI

docs/who-is-using.md
Add [Inter&Co](https://inter.co/) to who is using the SparkOperator.
=> :memo: Add Inter&Co to who-is-using.md

charts/spark-operator-chart/Chart.yaml, charts/spark-operator-chart/README.md
Close #2034.
- Revert chart appVersion to `v1beta2-1.4.6-3.5.0`.
- [] I have added tests that prove my changes are effective or that my feature works.
=> Bump appVersion to v1beta2-1.5.0-3.5.0

OWNERS
- Add myself @ChenYi015 as spark-operator reviewer
I am currently a member of Kubeflow organization. 
Contributed PRs: https://github.com/kubeflow/spark-operator/pulls?q=is%3Apr+author%3AChenYi015
=> Add ChenYi015 as spark-operator reviewer

CODE_OF_CONDUCT.md, CONTRIBUTING.md
- ~~Add [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md).~~
- Add  `CODE_OF_CONDUCT.md` and redirect it to the [Kubeflow website code of conduct](https://www.kubeflow.org/docs/about/contributing/#follow-the-code-of-conduct).
- Update `CONTRIBUTING.md` to redirect to the [Devloper Guide](https://www.kubeflow.org/docs/components/spark-operator/developer-guide/).
=> Add code of conduct and update contributor guide

OWNERS
Add myself to Spark operator approvers so I can approve and merge PRs.
Contributed PRs: https://github.com/kubeflow/spark-operator/pulls?q=is%3Apr+author%3AChenYi015
=> Add @ChenYi015 to approvers

ADOPTERS.md
- <Change 1>
- <Change 2>
- <Change 3>
=> Add Alibaba Cloud to adopters

OWNERS
[jacobsalway](https://github.com/jacobsalway) has been consistently making quality contributions to the project. Adding him as a reviewer.
=> Added jacobsalway as a reviewer

internal/controller/sparkapplication/controller.go
Add extra logging for failing creation of ingressUI. 
=> Add specific error in log line when failed to create web UI service

.github/dependabot.yml
Reduce the frequency of Dependabot PRs for Go dependencies by only running monthly and by grouping PRs.
Ref: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
=> Group monthly dependabot updates for gomod

.github/dependabot.yml
* Revert https://github.com/kubeflow/spark-operator/pull/2190
* The dependency grouping can contain unwanted bumps e.g. controller-runtime https://github.com/kubeflow/spark-operator/pull/2196
=> Revert "Group monthly dependabot updates for gomod (#2190)"

OWNERS
- Add @ImpSy as Spark operator reviewer
- Contributed PRs: https://github.com/kubeflow/spark-operator/pulls?q=is%3Apr+author%3AImpSy
=> Add @ImpSy as reviewer

.github/workflows/integration.yaml, charts/spark-operator-chart/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml, charts/spark-operator-chart/crds/sparkoperator.k8s.io_sparkapplications.yaml, config/crd/bases/sparkoperator.k8s.io_scheduledsparkapplications.yaml, config/crd/bases/sparkoperator.k8s.io_sparkapplications.yaml
- Add CI check for generating CustomResourceDefinition, RBAC and WebhookConfiguration manifests.
- Add CI check for generating code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
- [] I have added tests that prove my changes are effective or that my feature works.
=> Add check for generating manifests and code

internal/webhook/sparkpod_defaulter.go
- fix: executor container security context does not work
=> Fix: executor container security context does not work

OWNERS
Discussed offline on Slack and during community Zoom call today with fellow maintainers
In recognition of consistent quality contributions from jacobsalway, the community agreed to make him an approver. Look forward to seeing even greater work from him!
=> Promoted jacobsalway from reviewer to approver

ADOPTERS.md
=> Add Ninja Van to adopters

.github/workflows/integration.yaml, charts/spark-operator-chart/tests/controller/deployment_test.yaml, charts/spark-operator-chart/tests/webhook/deployment_test.yaml
- Add helm unittest step to integration test workflow
- Fix container security context helm unit test
=> Add helm unittest step to integration test workflow

proposals/README.md
cc @kubeflow/kubeflow-steering-committee
=> docs: Add information about KEP process

internal/controller/sparkapplication/submission.go, pkg/common/spark.go
- Change the env set up from spark.kubernetes.driverEnv.%s to spark.executor.env.%s in method executorSecretOption
=> change env in executorSecretOption

ADOPTERS.md
=> Add APRA AMCOS to adopters

Dockerfile, config/samples/v1beta1_sparkapplication.yaml, config/samples/v1beta2_scheduledsparkapplication.yaml, config/samples/v1beta2_sparkapplication.yaml, examples/spark-pi-configmap.yaml, examples/spark-pi-custom-resource.yaml, examples/spark-pi-dynamic-allocation.yaml, examples/spark-pi-kube-scheduler.yaml, examples/spark-pi-pod-template.yaml, examples/spark-pi-prometheus-servlet.yaml, examples/spark-pi-prometheus.yaml, examples/spark-pi-python.yaml, examples/spark-pi-scheduled.yaml, examples/spark-pi-ttl.yaml, examples/spark-pi-volcano.yaml, examples/spark-pi-yunikorn.yaml, examples/spark-pi.yaml, spark-docker/Dockerfile, test/e2e/bad_examples/fail-application.yaml, test/e2e/bad_examples/fail-submission.yaml
=> Upgrade to Spark 3.5.5

CHANGELOG.md
=> Add changelog for v2.1.1

internal/controller/sparkapplication/submission_test.go
This PR adds unit tests for some of the submissions functions. 
- Add unit tests
Looks like unit tests were commented out as part of the migration process. Trying to add some of them back for code quality.
=> add unit tests for driver and executor configs

docs/user-guide.md
Fix typo in github pages
- Fix typo in github pages
=> Fix typo in github pages

examples/spark-pi-configmap.yaml, examples/spark-pi-custom-resource.yaml, examples/spark-pi-dynamic-allocation.yaml, examples/spark-pi-kube-scheduler.yaml, examples/spark-pi-pod-template.yaml, examples/spark-pi-prometheus-servlet.yaml, examples/spark-pi-prometheus.yaml, examples/spark-pi-python.yaml, examples/spark-pi-scheduled.yaml, examples/spark-pi-ttl.yaml, examples/spark-pi-volcano.yaml, examples/spark-pi-yunikorn.yaml, examples/spark-pi.yaml
- Adding securityContext to spark examples
Refer to discussions here #2401 
CC @juliusvonkohout
=> Adding securityContext to spark examples

internal/controller/sparkapplication/monitoring_config_test.go
Looks like unit tests were commented out as part of the migration effort. This PR adds it back with some fixes. 
- Add unit tests for monitoring config
=> fix and add back unit tests

Makefile, go.mod, internal/controller/sparkapplication/controller.go, internal/controller/sparkapplication/driveringress.go, internal/controller/sparkapplication/driveringress_test.go, internal/controller/sparkapplication/event_filter.go, internal/controller/sparkapplication/event_handler.go, internal/controller/sparkapplication/monitoring_config.go, internal/controller/sparkapplication/monitoring_config_test.go, internal/controller/sparkapplication/submission.go, internal/controller/sparkapplication/web_ui.go
=> Get logger from context

.golangci.yaml, Makefile, internal/controller/scheduledsparkapplication/controller.go, internal/controller/sparkapplication/driveringress.go, internal/controller/sparkapplication/driveringress_test.go, internal/controller/sparkapplication/submission.go, internal/scheduler/kubescheduler/scheduler.go, internal/scheduler/volcano/scheduler.go, internal/scheduler/volcano/scheduler_test.go, internal/webhook/sparkpod_defaulter.go, internal/webhook/sparkpod_defaulter_test.go, pkg/util/metrics.go, pkg/util/sparkapplication.go, pkg/util/util.go, pkg/util/util_test.go
Golangci-lint has already released a v2 version of the linter, but the project is still running v1. The configuration file syntax has also changed, so I updated it. When I rerun the linters, they catch several errors (uncaught errors, etc.), so I fixed those as well.
Update Golangci-lint version with config file
Fix errors detected by linters
=> Update golangci lint

README.md
Add OpenSSF badge for Kubeflow Graduation.
It would also be great if any of the maintainers could update the questionnaire on [the BadgeApp website](https://www.bestpractices.dev/en/projects/10524). It requires you to authenticate with your GitHub but after that you can  edit the questionnaire.
Add OpenSSF badge for Kubeflow Graduation
N/A
=> chore: Adding OpenSSF Badge

Dockerfile, config/samples/v1beta2_scheduledsparkapplication.yaml, config/samples/v1beta2_sparkapplication.yaml, examples/spark-pi-configmap.yaml, examples/spark-pi-custom-resource.yaml, examples/spark-pi-dynamic-allocation.yaml, examples/spark-pi-kube-scheduler.yaml, examples/spark-pi-pod-template.yaml, examples/spark-pi-prometheus-servlet.yaml, examples/spark-pi-prometheus.yaml, examples/spark-pi-python.yaml, examples/spark-pi-scheduled.yaml, examples/spark-pi-ttl.yaml, examples/spark-pi-volcano.yaml, examples/spark-pi-yunikorn.yaml, examples/spark-pi.yaml, test/e2e/bad_examples/fail-application.yaml, test/e2e/bad_examples/fail-submission.yaml
This PR upgrades Spark to 4.0.0. 
There are some changes to core from 3.5 to 4.0 but as far as I can tell, they don't affect us: https://spark.apache.org/docs/latest/core-migration-guide.html#upgrading-from-core-35-to-40
There hasn't been many changes to spark-submit: https://github.com/apache/spark/commits/master/docs/submitting-applications.md
I do have some concerns:
- are we going to maintain a separate branch for spark 3 for those who haven't or cannot upgrade to 4 yet?
- if yes, do we need a separate release process / automation?
fixes: #2538 
- Update Dockerfile and examples to reference 4.0.0.
- Update Docker image references to use FQDN.
=> upgrade to Spark 4.0.0

charts/spark-operator-chart/templates/hook/cluster_role.yaml, charts/spark-operator-chart/tests/hook/cluster_role_test.yaml
=> Grant get/patch permissions for SparkConnect CRD to hook ClusterRole
